### ISSUE TITLE
Shall we set up a new mailing list ?

### ISSUE THREAD

**Issue by siteshwar** [att/ast#1013]
The lists under lists.research.att.com are not working anymore. Also, it's unlikely they will be made functional again and will not be kept well maintained in future. I would like to hear comments about if we should set up a new mailing list. If yes, what mailing list providers we can use.

**Comment by krader1961** [comment]
I am ambivalent. As a grey-beard who earned his first check as a programmer in 1979 I have spent most of my professional life using, and relying on, mailing lists. I think they still have a role but mostly in a read-only mode to communicate changes from the development team to interested parties. As a mechanism for discussing changes or asking for help it seems that mechanisms like Github issues and the [Caddy web server](https://caddy.community/) forum are now the norm. So is it really worthwhile to setup a new mailing list? Especially since you would need to get a significant number of people who subscribed to the old mailing lists to switch to the new lists. And since we can no longer send messages to the old lists it is unclear how to communicate to that audience they need to subscribe to a new mailing list.

A new mailing list. If only to do nothing more than broadcast announcements is is probably a good idea. But for "how do I do X?" and "I found a bug" type messages it seems like Github issues, possibly augmented by other community discussion forums (including StackExchange/StackOverflow) is probably sufficient.

**Comment by siteshwar** [comment]
> I think they still have a role but mostly in a read-only mode to communicate changes from the development team to interested parties.

While I agree that majority of the developers/users are on GitHub, there are still some people who are either not on GitHub or do not want to use it. Mailing list is best way to communicate with such people. It's true that new mailing list is going to be low on traffic, calling it 'read-only' is not correct.

> And since we can no longer send messages to the old lists it is unclear how to communicate to that audience they need to subscribe to a new mailing list.

We will just update readme file on GitHub. People who are still interested in `ksh` will eventually get there at some point.

**Comment by kusalananda** [comment]
If there was a mailing list, I would be on it instead of following the developers' discussions here (which are interesting, but rarely useful to me personally, unless I think I have something to say about the actual development of the ksh shell).

A mailing list, depending on how it is presented, may primarily serve users and allow them to ask support type questions (for when sites like unix.stackexchange.com or other user-driven forums are not enough (I sometimes refer users from there to project-specific mailing lists for expert advice)).  Those types of discussions may not be wanted as issues on GitHub, and GitHub issues could remain primarily focused on the actual development of the shell.

I don't know that "most users are on GitHub".  Most users that are interested enough to sign up to a ksh mailing list might be on GitHub, but that does not preclude the existence of a mailing list.

In the end, the ksh developers (you guys) will have to sort out how development business and user support business is best handled. Personally, I would want to keep user support away from GitHub, but that's just personal opinion.

**Comment by siteshwar** [comment]
> If there was a mailing list, I would be on it instead of following the developers' discussions here (which are interesting, but rarely useful to me personally, unless I think I have something to say about the actual development of the ksh shell).

I agree with your sentiment, but I also feel that current `ksh` development is slightly disconnected from end users. That's why I would like to hear more comments from people like you and others, who are still interested in using `ksh`. It's very likely that we would create a new list for users that can be used for announcements, getting help etc. But I would still appreciate your continued involvement on GitHub.

**Comment by krader1961** [comment]
@kusalananda I'm inclined to agree with your viewpoint. The reason I said earlier that such as list would be mostly read-only is that these days it seems most users who need help are likely to use StackExchange or similar mechanisms. In fact, we might be better served by setting up a Discord channel or whatever is at the heart of the [Caddy Web Server Community](https://caddy.community/) mechanism as ways for people to ask for help with ksh issues.

Having said that I think we should have a mailing list for a) announcements, and b) for those people who prefer interacting by email. I have hosted mailing lists in the past but have no interest in doing so now. In the absence of a corporate entity willing to host the list(s) the only viable option is setting up a [Google Group](https://groups.google.com/forum/#!overview).

**Comment by McDutchie** [comment]
+1 to a mailing list.

-10 to Google Groups. They are horrible. Try [freelists.org](https://www.freelists.org/).

**Comment by krader1961** [comment]
> -10 to Google Groups. They are horrible. Try freelists.org.

I have no reason to think Google Groups mailing lists are horrible. In my experience the mailing lists they mediate work well. Obviously Google is a company who monetizes any information they have access to. Which is itself problematic. But that is true for any third-party we utilize, including freelists.org. So I'm wondering why using freelists.org is any better other than on the general principal that diversity is preferable to monopolies.

@McDutchie Why should we trust freelists.org to be a) more stable and long lasting than google groups, and b) that they won't leverage our data? Since we wouldn't be paying either manager of our mailing lists why should we prefer freelists.org over groups.google.com? Note that Google Groups was itself an important archive of messages to the [Deja News](https://en.wikipedia.org/wiki/Google_Groups) service. I was an active user during that transition and was thankful that Google kept that archive accessible.

**Comment by siteshwar** [comment]
@McDutchie Unfortunately Google Groups is also the suggestion I have received offline from other people. Do you have any specific bad experience with them ? 

I am curious if people will refuse to sign up for the list, just because it's on Google groups.

**Comment by krader1961** [comment]
On Google Groups there are two lists ostensibly about this project:

https://groups.google.com/forum/#!forum/alt.comp.lang.shell.unix.korn
https://groups.google.com/forum/#!forum/kornshell

Both are effectively dead and the content is mostly spam. I've gone ahead and created a new list at `korn-shell@googlegroups.com` and https://groups.google.com/d/forum/korn-shell. I couldn't use `ksh@...` because group names have to be at least four characters.

For now I've configured it to require being a member of the group to post a message but anyone can join. That's to minimize the amount of spam that has to be managed. We'll probably want to change that to allow anyone to post a message but at this time I'm not comfortable allowing that until we have more people managing the group.
