### ISSUE TITLE
.DIG, .MIN, .MAX and related sub-variables

### ISSUE THREAD

**Issue by siteshwar** [att/ast#1017]
In `ksh93v-` release `.DIG`, `.MIN`, `.MAX` and few other attributes were added to integer, float and enum types. Related notes from release file:

```
13-08-27 +enum constants can have .DIG, .MAX, or .MIN sub-variables.
13-08-26 +Floating variables can be following by DIG, MAX, MIN, EPSILON,
	  INT_MAX, INT_MIN, or MAX_10_EXP to give values correspond to
 	  the floating type of the variable.
13-08-26 +Integer variables can be followed by .DIG, .MAX, or .MIN in
	  arithmetic expression so give the values corresponding to that
	  integer type.
```

What is the usefulness of these attributes in a shell script ?

**Comment by krader1961** [comment]
For those wondering how to use those attributes note they are only available in math context, not simple parameter expansion. For example:

```
$ integer i
$ echo $(( i.MIN ))
-9223372036854775808
$ echo $(( i.MAX ))
9223372036854775807
$ echo $(( i.DIG ))
19
$ float f
$ echo $(( f.EPSILON ))
1.08420217248550443e-19
```

Whereas `echo ${i.MIN}` outputs nothing.

Like @siteshwar I am left scratching my head over the reason this was implemented.

**Comment by dannyweldon** [comment]
Because languages evolve.  Remember how simple `BASIC` was originally with line numbers and `GOTO` statements?  Then it went procedural; then object oriented.  That's just one example.  `ksh` is not `dash`.  It is more like `tclsh`, or it aspires to be like `tcl`.  IMHO.

**Comment by krader1961** [comment]
Given the nature of the ksh DSL there is no way for these attributes (i.e., values) to be used programmatically. And as information a human might want to know it is simpler to just document that ksh uses the `long double` type and expect the user to lookup what that means for their platform. This is the type of "feature" that is of dubious value that caused me to abandon `zsh`.

**Comment by dannyweldon** [comment]
The real issue here is the incorrect perception that ksh is just another dumb, stupid, posix cli shell, which it is *not*.  Once that is understood, it's a complete no-brainer that this code is useful and that it should stay, or an alternative should be provided.  Is it being removed because it is buggy?  No.  Because it's complex?  No.  Is it useful?  YES!!!  Which is why every other scripting language provides a similar thing!

> Like @siteshwar I am left scratching my head over the reason this was implemented.

Then why are these constants present in pretty-much all other languages?  Stop with the excuse of "why would someone do that in a shell script".

> @dannyweldon I don't grok your comment. Are you saying that someone will ever write a ksh script ("program" if you prefer) that explicitly tests the characteristics of the native integer/float types using this mechanism and either adapt its behavior or refuse to continue if they don't meet some minimum standard (e.g., 64 bit ints)? That seems extremely unlikely. Especially since the nature of the language makes comparisons to these constants problematic.

That is not the only use case.  Some research reveals that people use these constants to check for or prevent numeric overflow during calculations.

> Especially since the nature of the language makes comparisons to these constants problematic.

That's not true because they work perfectly in a numeric context which can be used in an expression in combination with any other.

> I am an advocate of introspection. I added introspection features to the fish shell. And on that basis alone I might be willing to keep this feature.

So ksh is not good enough?  It never will be good enough if decent features keep getting discarded.

> But to suggest it would ever be used in a real-life ksh script seems far-fetched.

Then why were mathemeticians raising bugs about them in the mailing list?  (And other maths features.)

https://www.mail-archive.com/ast-users@lists.research.att.com/msg00648.html


> Primary use case of ksh is as a shell interpreter.

That's not my primary use case.  And I doubt for many others.  My primary use case is as a scripting language.

> Trying to compete with languages like tcl , python etc. is going to do no good to this project.

I completely disagree and strongly believe that this was it's intended direction.

> We should aim for backward compatibility and stability,

That's fine.  Once that is done, then what?

> rather than trying to copy every other feature from such languages.

Well, probably not every feature, but such is the nature of programming languages.  They adapt.

As maintainers, it's fine if you don't have the interest to improve the language, but please don't discard perfectly good code because you personally can't see the benefit.  Try asking `python` to drop math constants and see how far you get.

> Given the nature of the ksh DSL there is no way for these attributes (i.e., values) to be used programmatically.

Again, this is false, as they can be used programatically.

> And as information a human might want to know it is simpler to just document that `ksh` uses the long double type and expect the user to lookup what that means for their platform.

And that would be a real pita.  And as stated above, that's not nearly the only use case as they can be used to test for arithmetical overflow without caring what the platform size is.

> This is the type of "feature" that is of dubious value that caused me to abandon `zsh`.

This is completely unlike the hodge podge of `zsh` "features" which I also dislike.

An alternative, would possibly be to define the constants under `.sh.math` as can be done currently:

    integer .sh.math.INT_MAX
    integer -r .sh.math.INT_MAX=$(( .sh.math.INT_MAX.MAX ))

Of course, one could also just do:

    integer INT_MAX
    integer -r INT_MAX=$(( INT_MAX.MAX ))

But I think having sub variables has merit as one then does not have to care what the type of the maths variable is.

**Comment by DavidMorano** [comment]
>> Primary use case of ksh is as a shell interpreter.

> That's not my primary use case. And I doubt for many others. My primary use case is as a scripting language.

I also disagree with the idea that KSH was or is primarily a shell interpreter.
For me it is foremost -- much more so than either TCL or Python -- a programming (scripting) language. KSH predates all of those and more. Although I love AWK, I even use KSH in many places where AWK would be very simple to use. And Perl ... cough ... I never felt the need to get onto the Perl bandwagon when one is proficient in KSH. Perl was supposed to be the combination of SH, AWK and C. Well, for me, it did not turn out that way. I was very proficient with those languages already, so Perl did not tickle my cookie like it did so many others.

>>Trying to compete with languages like tcl , python etc. is going to do no good to this project.

> I completely disagree and strongly believe that this was its intended direction.

Yes, I thought that TCL was going someplace back in 1994 or so (I invested heavily in learning it, silly me), but where is it today? Look, I have nothing against TCL or Python per se, but they did not automatically replace what can be done in KSH. Yes, I am an unusual case (I guess that I have to say that at this point). I have been using KSH for about 35 years. I have seen them (other stupid-a*s languages come and go), but KSH has remained -- than you very much. KSH is now quite old (as these new programming languages go), but was indeed evolving into newer spaces. I think that it should eventually continue to evolve into newer spaces once a new stable release is produced. The last thing I would want to see happen, is for KSH to stagnate.

**Comment by siteshwar** [comment]
> Well, probably not every feature, but such is the nature of programming languages. They adapt.

And they also end up making life of existing users miserable. Python2 to python3 was a nightmare and so is Perl 5 to Perl 6. When we add a new feature to `ksh`, we have to keep a promise that it won't break in future. It should not be done unless new features get heavily debated. That's why I am disabling those experimental features. Any maintainer who has seen code for last beta release will agree with us. It has introduced more bugs than it fixed.

> That's fine. Once that is done, then what?

Our first priority is to release a version of ksh that is acceptable to existing users. This may not sound much, but given the health and state of this project, it's a very ambitious target. If we manage to do it, our future directions should be left to be discussed with community. At this point I can not think beyond next release. Despite of being so cautious, I am pretty sure we are still going to break lot of scripts.

**Comment by siteshwar** [comment]
> For RHEL at least, would it be possible to provide multiple versions, as I believe RHEL 8 now uses App Streams? So, make the default stream the latest version, but if customers find they have problems, they can just switch back to the last stable ksh release which would be on a different stream.

That's the plan. I will either do multiple packages or provide a module for it. I am going to recommend same to other vendors too. Migration path from old to new version of ksh has to be smooth.

**Comment by krader1961** [comment]
> Again, this is false, as they can be used programatically.

and

> they can be used to test for arithmetical overflow without caring what the platform size is.

Okay, I see I badly phrased my assertion. What I was trying to say is that anyone who cares about overflow (or underflow), and has the requisite knowledge to write the necessary tests using these constants, is unlikely to use ksh to solve their problem. In the context of ksh it would be better to simply make it impossible to inadvertently cause overflow. Possibly by introducing a new type of `trap` where the default trap would terminate the script with an appropriate diagnostic.

**Comment by dannyweldon** [comment]
> In the context of ksh it would be better to simply make it impossible to inadvertently cause overflow. Possibly by introducing a new type of trap where the default trap would terminate the script with an appropriate diagnostic.

Interesting.  I can think of good and bad sides to it though.
