### ISSUE TITLE
sed: /src/lib/libast/include/sfio.h: No such file or directory

### ISSUE THREAD

**Issue by ryandesign** [att/ast#1110]
**Description of problem:**

After I run meson, in meson-log.txt I see these lines:

```
sed: /src/lib/libast/include/sfio.h: No such file or directory
sed: /src/lib/libast/include/sfio.h: No such file or directory
```

Should I be seeing that?

I think it is because conf.tab includes these lines:

```
SF_BUFSIZE			AST	XX 1 MUX	sh{
	sed -e '/[ 	]*#[ 	]*define[ 	][ 	]*SF_BUFSIZE[ 	]/!d' -e 's/^[^0-9]*//' -e 's/[^0-9]*$//' $PACKAGEROOT/src/lib/libast/include/sfio.h
}
```

I presume `$PACKAGEROOT` is not defined.

**Ksh version:**

20190108

**How reproducible:**

Always

**Steps to reproduce:**
1. Run meson

**Actual results:**

Error in meson-log.txt

**Expected results:**

No error in meson-log.txt

**Additional info:**

**Comment by krader1961** [comment]
> I presume $PACKAGEROOT is not defined.

Correct. That is defined by the legacy Nmake+IFFE based build system, not Meson. This bug means the ksh `getconf` builtin won't be able to report the value for `SF_BUFSIZE`. Which should be harmless since it is highly improbable there is a ksh script anywhere in the world which does `getconf SF_BUFSIZE`. Especially since it isn't available in the last stable release. So while we could fix this I'm going to just remove it.
