### ISSUE TITLE
ksh missing set -E, set -o pipefail ?

### ISSUE THREAD

**Issue by mcandre** [att/ast#1115]
In OpenBSD 6.3, ksh set appears to lack the -E and -o pipefail features, important for ensuring that scripts execute in a more robust manner, similar to bash scripts. Are these features available in more recent ksh commits? Perhaps OpenBSD is pinned to an older ksh version..

**Comment by kusalananda** [comment]
On OpenBSD, the `ksh` executable is not `ksh93` but a modified version of `pdksh` (a `ksh88` lookalike, similar to `mksh`).  To use `ksh93` on OpenBSD, install the `ksh93` package.  That package provides `ksh93` "Version AJM 93u+ 2012-08-01".

The `ksh` in the OpenBSD base system will likely never get those `set` attributes, as they are not needed for running the OpenBSD base system.

**Comment by krader1961** [comment]
I have OpenBSD 6.2 rather than 6.3 but that probably doesn't matter. Running `man ksh` reports: `ksh, rksh – public domain Korn shell`. Which is pdksh as @kusalananda explained. In you install Meson and Ninja you should be able to build the current master branch of this project which will give you ksh93v- more or less.
