### ISSUE TITLE
Analyze changes made after last stable release (ksh93u+)

### ISSUE THREAD

**Issue by siteshwar** [att/ast#1116]
`ksh93u+` was last stable release that was embraced by various distributions. We should analyze all the changes made after this release. Any backward incompatible changes should be reverted. If there is a new feature that's worth mentioning, it should be mentioned in `CHANGELOG.md` file. Changes can be found [here](https://github.com/att/ast/blob/5cedc989a424ddcb54ba5c2c19c9c36cbeffbefd/src/cmd/ksh93/RELEASE#L1-L655).

**Comment by krader1961** [comment]
FWIW, Any introduction of a new builtin is strictly speaking not backward compatible since the new builtin may have different behavior than the platform's external command of the same name. Which is why @siteshwar removed a few new builtins such as `date`. See issue #990 where I raised the question whether the `tmxdate()` function should be removed or the builtin `date` reinstated in order to justify the cost of maintaining the *src/lib/libast/tm/tmxdate.c* code. Of course, removing `tmxdate()` introduces it's own backward incompatible change. Specifically, `sleep '7 day'` won't be supported. But since that has never been documented it should be acceptable.

**Comment by siteshwar** [comment]
We should revert this change:

```
306 13-05-22 +Added -c option to typeset which is similar to typeset -m except
307       that the variable is copied rather than moved.  This is experimental
308       and there are known bugs.  If it can't be made reliable it will
309       not be added.
```

**Comment by siteshwar** [comment]
Could this change cause issues with compatibility ?

```
13-05-29  ksh93 now intercepts the `LC_TIME` variable.
```

**Comment by siteshwar** [comment]
Another experimental change:

```
226 13-07-30 +An experimental change to each enumeration variable have sub-variables
227       for each enumeration constant.  ${enum.name} will expand to the
228       numerical value of the enumeration name associated with enum.
```

**Comment by siteshwar** [comment]
```
182 - 13-05-29  namespace commands are no longer allowed inside function definitions
183       and now generate a syntax error.
```

This is a backward incompatible change too. But it looks like a sane change that can be easily worked around in scripts by moving namespace definitions outside functions. I will keep it.
