### ISSUE TITLE
`_pipe_socketpair` has to be true otherwise io.sh unit test fails

### ISSUE THREAD

**Issue by krader1961** [att/ast#1147]
While working to resolve issue #1120 it seemed to me we should be able to build ksh without the use of `socketpair()`. So I changed the definition of `_pipe_socketpair` in *config_ast.h.in* from one to zero. But that causes several failures in the *io.sh* unit test. I also verified that the ksh93v- branch fails the same tests in the *io.sh* unit test if I force that preprocessor symbol to be false (or undefined).

P.S., No other shell I have examined (which includes bash, zsh, fish, elvish) require the use of `socketpair()`. On basic principals alone it shouldn't be necessary to use `socketpair()` in a POSIX shell. I am thus mystified as to why the AST team implemented this

**Comment by DavidMorano** [comment]
@krader1961 

On the use of |socketpair(3xnet)|

If no one else wants to answer this, I will try. I have not looked at the relevant KSH code (or the latest pipe implementations) in ages though, so it is anyone's guess what the current situation is.

|socketpair()| is required by KSH on those OSes that do not have a PEEK type of function available for use on their pipes. On systems that do not have peek for pipes, KSH switches to using sockets instead of pipes in order to get the PEEK feature available with standard sockets.  All known, or cared about, socket implementations support a PEEK function on a socket. I am not totally sure, but I think that the KSH |read(1ksh)| built-in used to want to do a peek on its input. So that might be one example where KSH required a peek-type function.  This requirement spreads backwards like a cancer and ends up requiring KSH to use sockets instead of pipes for making some pipe-type-IO between processes in a process group.

I do not know about the most recent Linux OS (although I probably should), but even the latest Linux might not yet support a peek function on its pipes. At least all SysV based OSes have supported a peek on pipes since (basically) eternity past, so those OSes were never a problem, and therefore did not require any sockets at all.

**Comment by krader1961** [comment]
> At least all SysV based OSes have supported a peek on pipes since (basically) eternity past

That is true for SVR4 but is not true for SVR3 and earlier. This is based on my experience with Sequent DYNIX/3 (which had a SVR3 "universe") and DYNIX/ptx which was based on SVR4. AT&T System V Release 4 dates back to 1988 so that is, in IT terms, an "eternity past". What I sense here is a theme. Namely the influence of the Solaris devs and users having way too much influence on the development of ksh.

None of which changes my observation that other shells manage to implement features like reading a specific number of characters with a timeout without requiring the ability to peek into what is in a pipe.

**Comment by krader1961** [comment]
And note that this dependency on `socketpair()` (or a SVR4 STREAMS based pipe) also means we have both `sh_pipe()` and `sh_rpipe()`. The latter being needed to ensure we get a "real" pipe rather than a `socketpair()`.

**Comment by DavidMorano** [comment]
@krader1961 
>None of which changes my observation that other shells manage to implement features like reading a specific number of characters with a timeout without requiring the ability to peek into what is in a pipe.

Yes, KSH had or may still have a fall-back option for reading the input out of a (real) pipe one character at a time, so as not to read past the end-of-line (if I remember) character. Whether any fall-back code is still in the KSH code base or not, I do not know. Presumably KSH would have had to do this on OSes without either a peek on pipe or any sockets (a possibility on some OSes a few decades ago).

**Comment by krader1961** [comment]
> Yes, KSH had or may still have a fall-back option for reading the input out of a (real) pipe one character at a time, so as not to read past the end-of-line (if I remember) character.

While I could quibble with your wording I suspect you are correct, @DavidMorano.  The reason this peeking behavior, and thus the use of `socketpair()`, was implemented was a performance optimization. Which suggests the old ksh dev team failed to recognize that ksh would never be an alternative to other languages that don't have to conform to POSIX 1003. Because this optimization isn't significant for 99.999% of ksh scripts.

**Comment by krader1961** [comment]
Closing as a duplicate of #462.
