### ISSUE TITLE
`getconf -v=PATH` causes coredump

### ISSUE THREAD

**Issue by siteshwar** [att/ast#1174]
**Description of problem:**
From `getconf` man page:

```
  -v, --specification=name
                  Call the native getconf(1) with option -v name.
```

**Ksh version:**
2017.0.0-devel-2380-gc0aaf51f

**How reproducible:**
Always

**Steps to reproduce:**
```
builtin getconf
getconf -v=PATH
```

**Actual results:**
```
Memory fault(coredump)
getconf: /bin/getconf: exec error [267]
```

**Expected results:**
```
/usr/bin
```
or value of `PATH` variable depending on OS.

**Additional info:**
This bug is present in both `ksh93u+` and `ksh93v-` releases.

**Comment by krader1961** [comment]
As I have already argued elsewhere I don't believe `getconf` should be an optional builtin. Even for scripts that use `getconf` having it be available as a builtin will not noticeably improve the performance of the script. And for any script that uses `getconf` it should be possible for the script to use the command provided by the platform. In fact, given the numerous problems with this code, it is probably better for the script to use the version provided by the platform. Note my use of the phrase "optional builtin". This builtin is not enabled by default despite its mention in the main *ksh.1* man page (the only optional builtin with such a mention).

**Comment by krader1961** [comment]
See issue #1118 for why I think we should just eliminate this code rather than fix its bugs. Even if we can't remove it before the next release we should not expend any effort fixing the bugs in the code. There is no good reason to fix these bugs since any script relying on the current, buggy, builtin are presumably working fine despite those bugs. And in all likelihood those uses will be satisfied by the platform `getconf` external command.

**Comment by krader1961** [comment]
Closing since we've removed the `getconf` builtin making this issue moot.
