### ISSUE TITLE
`uname -d` should print domain name returned by `getdomainname`

### ISSUE THREAD

**Issue by siteshwar** [att/ast#1184]
**Description of problem:**
`uname -d` causes a crash.

**Ksh version:**
2017.0.0-devel-2407-gdd1f44d3

**How reproducible:**
Always

**Steps to reproduce:**
```
builtin uname
uname -d
```

**Actual results:**
It causes `ksh` to crash.

**Expected results:**
It should print domain name returned by `getdomainname`.

**Additional info:**
It does not cause a crash in `ksh93v-` release.

**Comment by krader1961** [comment]
Works for me on macOS and other BSD. Albeit it is not useful since it outputs `[domain]`. But then I don't run NIS/YP on any of my systems. Having said that the implementation is obviously broken:

```
        if (flags & OPT_domain) {
            s = astconf("SRPC_DOMAIN", NULL, NULL);
            if (!(*s)) getdomainname(s, sizeof(buf));

            output(OPT_domain, s, "domain");
        }
```

Notice that it is passing the pointer returned by `astconf()` to `getdomainname()` while telling that function the pointer is to a buffer of size `sizeof(buf)`. Bzzt! Wrong!

This feature isn't in the ksh93u release so I vote we simply remove it rather than fix it.
