### ISSUE TITLE
Any plans to make new release?

### ISSUE THREAD

**Issue by kloczek** [att/ast#1238]
This is not a bug report. Just humble question about make new release.
I know that there is a lot of still not resolved issues but at the same time make new release always helps involving more people into fixing most important issues.

And if I make ask to make release using widely used versioning convention like <major_ver>.<minor_ver>[.<sub_minir_ver>] or at least something like 201903.1 or 2019.<minor_ver> :)

**Comment by siteshwar** [comment]
> This is not a bug report. Just humble question about make new release.
> I know that there is a lot of still not resolved issues but at the same time make new release always helps involving more people into fixing most important issues.

Agreed. But at the same time code should be in a shape that makes it easier to debug issues. Otherwise it would be very hard to involve more people. That's why we are trying to simplify codebase and adding more tests to avoid creating regressions. Until we make a release, you can use latest ksh from our copr or OBS repos. Also, there are some other downstream maintainers who are shipping latest version, for e.g. Mageia.

> 
> And if I make ask to make release using widely used versioning convention like <major_ver>.<minor_ver>[.<sub_minir_ver>] or at least something like 201903.1 or 2019.<minor_ver> :)

We have switched to semantic versioning through #335.

**Comment by kloczek** [comment]
Few hours ago I've testes ksh93 from Fedora trying to use it as sh building gcc.
All froze at some point and this is why I've turned my attention to this repo :P

Simple I'm looking for as much fast as possible 100% POSIX sh compliant interpreter because many things in gcc build process relies on not parallel sh.
In mean time I'm trying with mksh.

Nevertheless fixing bugs it is never ending story (in this word we are dealing with only not enough tested code :) ).
If you want to fix all possible bugs and then make release it will never gonna happen :P
In other words I would strongly encourage to make new release asap :)

**Comment by cschuber** [comment]
FreeBSD's ksh93-devel has been tracking HEAD for a while now. No complaints thus far. And people are migrating from ksh93, which is 93u, to the -devel port/package. It resolves many issues in ksh93u. And, updating the main port to 93v is more trouble as the build tools have changed over time. I'd welcome 93w.

**Comment by siteshwar** [comment]
> FreeBSD's ksh93-devel has been tracking HEAD for a while now. No complaints thus far. And people are migrating from ksh93, which is 93u, to the -devel port/package. It resolves many issues in ksh93u. And, updating the main port to 93v is more trouble as the build tools have changed over time. I'd welcome 93w.

@cschuber Thanks for packaging latest version in FreeBSD. Do you have any usage statistics about `ksh93-devel` package ?

**Comment by siteshwar** [comment]
I have been packaging upstream through Copr and OBS for a while now, but I don't have any statistics about how many people are actually subscribed to these repositories. If you are reading this thread and use one of these repositories (or directly build from upstream), feel free to provide any feedback in this thread.

**Comment by krader1961** [comment]
Over the past two years we've made huge improvements to the project. We replaced the legacy Nmake build system with Meson. We restyled the code (using `clang-format`) to have a consistent style. We restructured the existing unit tests to be hermetic and eliminate most of the flakey failures. We replaced the AST vmalloc subsystem with the platform malloc. We merged all the downstream fixes from Redhat, Solaris, etc. that we could find and which hadn't already been merged upstream. We eliminated tens of thousands of lines of code not relevant to building ksh. We fixed a huge number of bugs including some serious bugs such as functions that returned a pointer to a local stack var. We created a framework for running interactive tests using `expect` and have written quite a few such tests. Most recently @siteshwar has been adding more API level tests.

So why haven't we made a new release? The main reason is that there are still memory management bugs that show up under ASAN and Valgrind. The question is whether those should be blocking issues for a new release. On the one hand these are potentially serious bugs that could result in silent data corruption. On the other hand they involve ksh features that are probably unused in the vast majority of ksh scripts. Also, these bugs don't seem to cause any problems and we only know about them thanks to tools like ASAN. Which argues that these bugs should not block a new release.

P.S., If someone knows how to build ksh93u using Nmake (the `ast.master` branch) with ASAN enabled please tell us how to do so. I would feel a lot more comfortable creating a new release if we could show that these memory management bugs were also present in the ksh93u release.

**Comment by cschuber** [comment]
On March 21, 2019 2:57:33 PM PDT, Siteshwar Vashisht <notifications@github.com> wrote:
>> FreeBSD's ksh93-devel has been tracking HEAD for a while now. No
>complaints thus far. And people are migrating from ksh93, which is 93u,
>to the -devel port/package. It resolves many issues in ksh93u. And,
>updating the main port to 93v is more trouble as the build tools have
>changed over time. I'd welcome 93w.
>
>@cschuber Thanks for packaging latest version in FreeBSD. Do you have
>any usage statistics about `ksh93-devel` package ?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/att/ast/issues/1238#issuecomment-475418650

Unfortunately I do not. Only a few telling me they are people moving to the -devel port, hardly scientific.

I think that since ksh93u is so old and ksh93v has different build prerequisites that an interim release would resolve many issues currently being experienced in the older release.


-- 
Pardon the typos and autocorrect, small keyboard in use.
Cheers,
Cy Schubert <Cy.Schubert@cschubert.com>
FreeBSD UNIX: <cy@FreeBSD.org> Web: http://www.FreeBSD.org

	The need of the many outweighs the greed of the few.

**Comment by krader1961** [comment]
FWIW, I really, and I mean **really**, wish someone would figure out how to build the ksh93u branch (`ast.master`) and run its unit tests with ASAN enabled.  That's because I've just merged a couple of changes that eliminate stderr redirections to */dev/null* which reveal memory management bugs other than use-after-free. For example, a heap-buffer-overflow when running the `namespace` unit test. I would feel much more comfortable creating a new ksh release based on this code if we could show these problems exist in the legacy ksh93u code. That, however, is probably not possible because of the use of AST vmalloc rather than the system malloc in that version of the project.

My preliminary review of the code implicated in these ASAN failures strongly suggests these memory management bugs are present in the ksh93u code. Nonetheless, if someone can show how to build the `ast.master` branch and run its unit tests with ASAN enabled I would be willing to modify that branch to use the system malloc rather than AST vmalloc.

**Comment by krader1961** [comment]
I just identified and fixed another memory management bug that also exists in the ksh93u release (see issue #1261). That particular bug is unlikely to be exercised by any real world ksh script. Too, that bug is silent and harmless nearly all of the time on a typical computer system unless something like ASAN or Valgrind is enabled which detects the invalid memory access.

This increases my confidence that any remaining memory management bugs are either present in the ksh93u release (which is what all distros use as I write this) or so unlikely to be noticed as to be irrelevant.

**Comment by krader1961** [comment]
I've been chipping away at the memory management bugs identified by ASAN. We're now down to just two such failures (four if you include the `/shcomp` test variant) on macOS. And one of those failures is issue #1267 which isn't likely to ever be noticed outside of unit tests run with ASAN enabled since few scripts use the `nameref` builtin AFAICT.

My success at eliminating all but one problem identified by ASAN on macOS caused me, for the first time, to run the tests with ASAN enabled on a Linux platform. That reveals bugs not being caught by ASAN on macOS. But note that some of those are memory leaks which we expect from this code. I had already suppressed leak warnings on my macOS server. Apparently that needs to be done in some other fashion on OpenSuse 42.

 Whether the non-memory leak problems found by ASAN on OpenSuse are significant is TBD.

**Comment by krader1961** [comment]
Also, while I can't prove it, I believe the bug found by ASAN involving `nameref` has been present at least as far back as the ksh93u release based on a review of the code. Then and now.

**Comment by krader1961** [comment]
I've eliminated all but one bug found by ASAN (if you ignore memory leaks). The remaining bug is in how `trap` commands are handled and affect the `signal` unit test. It appears to be something unlikely to be a problem for 99.999% of scripts with ASAN enabled and without ASAN no one is likely to notice. So I'm comfortable closing this issue since there are no longer any impediments that I can see to a new ksh release.

**Comment by siteshwar** [comment]
To give a more clear answer of original question, we are planning to do an alpha release this week.
