### ISSUE TITLE
Preprocessor symbol SH_DICT defined in just four C modules

### ISSUE THREAD

**Issue by krader1961** [att/ast#1269]
While working to resolve an unrelated issue I noticed that `SH_DICT` is defined in just a handful of *.c* modules:

```
./src/cmd/ksh93/include/defs.h:#define SH_DICT (void *)e_dict
./src/cmd/ksh93/bltins/ulimit.c:#define SH_DICT "libshell"
./src/cmd/ksh93/bltins/umask.c:#define SH_DICT "libshell"
./src/cmd/ksh93/sh/streval.c:#define SH_DICT "libshell"
```

The situation is almost identical for the ksh93u+ and ksh93v- branches (`ast.master` and `ast.beta` respectively). The differences are due to other cleanups we've done.  It is ridiculous for those modules to be defining that symbol. It should be defined in a common header (e.g., *defs.h*) and/or by the build system.

Yes, this is nit-picking. These `#define`'s are something that might have been needed long ago. I'm opening an issue about it because the project has a plethora of such issues. I'm hoping that by highlighting this specific instance it will encourage others to not be afraid of cleaning up legacy cruft of this nature.

**Comment by DavidMorano** [comment]
> Yes, this is nit-picking. 

No, it is not nit-picking, or at least it should not be!
Besides having definitions in multiple places (bad enough on its own), Having different definitions in different source files (headers or otherwise) is a sign of (very?) poor design -- of some kind.
Further the prefix `SH` should stand for something, and this definition, and all others with the prefix `SH`, should be (as already stated) located in the same source header file.
