### ISSUE TITLE
"integer CNR=0; let CNR++" unexpectedly causes an ERR trap

### ISSUE THREAD

**Issue by sneyx1234** [att/ast#1330]
**Description of problem:**
Indicate error and trigger trap handler without an error.

**Ksh version:**

```
# print -v .sh.version
Version AJM 93u+ 2012-08-01
```

**How reproducible:**
Interactive and script mode.

**Steps to reproduce:**
1.
```
trap "print \"[TRAP: ERR: \${LINENO}]\""  ERR

integer    CNT
           CNT=0

        let CNT++
       #CNT=$(( CNT + 1 ))

typeset -p CNT

```

**Actual results:**
```
[TRAP: ERR: 7]
typeset -l -i CNT=1
```

**Expected results:**
```
typeset -l -i CNT=1
```

**Additional info:**

**Comment by krader1961** [comment]
Looks like a bug to me since the documentation implies (albeit doesn't say so in so many words) that the increment operator is legal and therefore should be legal when used in an expression following the keyword `let`. Note that doing `(( CNT++ ))` does not raise an error.

**Comment by krader1961** [comment]
This is working as intended. From the documentation of `trap`:

> If sig is ERR then action will be executed whenever a command has a non-zero exit status.

For the `let` command:

> The exit status is 0 if the value of the last expression is non-zero, and 1 otherwise.

The test case has `CNT` set to zero when the expression is evaluated and that is therefore the return value of evaluating the expression. Which, as the documentation states, causes `let` to return a non-zero status. Which in turn causes the `ERR` trap to be invoked. Whether or not this is sensible behavior doesn't really matter since we can't change it without a major release -- and perhaps not even then.

**Comment by sneyx1234** [comment]
OK -- good to know -- will replace "let" used for "Arithmetic Evaluation" in library code ... because trap handlers can interfere.
