### ISSUE TITLE
`read` prints spurious signal warning

### ISSUE THREAD

**Issue by McDutchie** [att/ast#1354]
**Description of problem:**
The `read` builtin writes a warning about signals received by subprocesses to standard error, even if job control is not active so such warnings should never appear.

**Ksh version:**

Version AJM 93u+ 2012-08-01
Version A 2020.0.0-alpha1-249-g7f81e750

**How reproducible:**

```
#! /bin/ksh
(
	mypid=$(sh -c 'echo $PPID')
	kill -s STOP "$mypid"
	echo "ok, SIGCONT received"
) &
read line
echo "your line was: $line"
kill -s CONT "$!"
```

**Steps to reproduce:**
1. Run the above script with ksh.

**Actual results:**

```
$ ksh test.ksh
test.ksh[7]: read: line 1: 24935: Stopped (SIGSTOP)
foo
your line was: foo
ok, SIGCONT received
```

**Expected results:**

```
$ ksh test.ksh
foo
your line was: foo
ok, SIGCONT received
```

**Additional info:**
n/a

**Comment by krader1961** [comment]
FWIW, on macOS this test fails with the platform `ksh`, `bash`, and `zsh` binaries. That is, all three hang rather than producing any output. The ksh binary built from the source at the time I write this also hangs without producing any output. I haven't tested this on any other platform but my experience with macOS suggests there is either an abstraction that is too granular or behavior that is platform specific which should be platform agnostic.

**Comment by McDutchie** [comment]
It doesn't hang on any of those. It reads a line from standard input (this is necessary as it's `read` that produces the spurious warning on ksh). You're supposed to type something and press enter. :)

Here's a clearer version:

```
#! /bin/ksh
(
	mypid=$(sh -c 'echo $PPID')
	kill -s STOP "$mypid"
	echo "ok, SIGCONT received"
) &
printf 'Type anything: '
read line
echo "your line was: $line"
kill -s CONT "$!"
```

**Comment by krader1961** [comment]
Doh! Yes, of course, the reproduction script "hangs" given that I wrote my previous comment when I was inebriated and expected the reproduction script to be self contained. I didn't expect to need to press the [enter] key. :smile:

Nonetheless, I can only reproduce this on FreeBSD 11.1 among the systems I use to test such things. So I'm curious, @McDutchie, what OS you are seeing this on? Obviously this is a bug but knowing the specific platforms it occurs on is important.

**Comment by McDutchie** [comment]
Sorry for omitting that info, my OS is macOS 10.14.5.

**Comment by krader1961** [comment]
I also tested this on macOS 10.14.15 (which is my current desktop OS) and cannot reproduce the problem. However, I've noticed something similar in the *src/cmd/ksh93/tests/b_jobs.exp* unit test. I had to special case the  backgrounding of `cat` because that caused the `cat` process to die from a SIGTSTP signal. Whereas, on every other platform I'm using for testing, it simply hangs; i.e., continues to try and read from the source. I would bet a $10 USD that this issue is related. That is, a quirk of how signals are handled.

**Comment by McDutchie** [comment]
How odd that you can't reproduce this on the same OS as me – I can still reproduce it consistently. Standard input needs to be on a terminal and `read` needs to wait for actual keyboard input to reproduce it. Are you doing that? If so, what could be different about our systems?

**Comment by krader1961** [comment]
> How odd that you can't reproduce this on the same OS as me...

Yes to your questions, @McDutchie. I do have my login shell set to `fish` which has some odd ideas about managing tty behavior. Seeing your `stty -a` output might be helpful for comparison against my stty settings. Still, that this is also reproducible on FreeBSD 11.1 under VMware makes it easier to debug since we have at least two platforms where the problem is exhibited.

**Comment by McDutchie** [comment]
I just installed `fish` from MacPorts. When I invoke ksh with the test script from a fish session, the results are identical: the problem is still reproduced.

All the same, here are my `stty` settings just in case.

```
$ stty -a
speed 9600 baud; 56 rows; 132 columns;
lflags: icanon isig iexten echo echoe -echok echoke -echonl echoctl
	-echoprt -altwerase -noflsh -tostop -flusho pendin -nokerninfo
	-extproc
iflags: -istrip icrnl -inlcr -igncr ixon -ixoff ixany imaxbel iutf8
	-ignbrk brkint -inpck -ignpar -parmrk
oflags: opost onlcr -oxtabs -onocr -onlret
cflags: cread cs8 -parenb -parodd hupcl -clocal -cstopb -crtscts -dsrflow
	-dtrflow -mdmbuf
cchars: discard = ^O; dsusp = ^Y; eof = ^D; eol = <undef>;
	eol2 = <undef>; erase = ^?; intr = ^C; kill = ^U; lnext = ^V;
	min = 1; quit = ^\; reprint = ^R; start = ^Q; status = ^T;
	stop = ^S; susp = ^Z; time = 0; werase = ^W;
$ fish
Welcome to fish, the friendly interactive shell
> stty -a
speed 9600 baud; 56 rows; 132 columns;
lflags: icanon isig iexten echo echoe -echok echoke -echonl echoctl
	-echoprt -altwerase -noflsh -tostop -flusho pendin -nokerninfo
	-extproc
iflags: -istrip icrnl -inlcr -igncr -ixon -ixoff ixany imaxbel iutf8
	-ignbrk brkint -inpck -ignpar -parmrk
oflags: opost onlcr -oxtabs -onocr -onlret
cflags: cread cs8 -parenb -parodd hupcl -clocal -cstopb -crtscts -dsrflow
	-dtrflow -mdmbuf
cchars: discard = ^O; dsusp = ^Y; eof = ^D; eol = <undef>;
	eol2 = <undef>; erase = ^?; intr = ^C; kill = ^U; lnext = ^V;
	min = 1; quit = ^\; reprint = ^R; start = ^Q; status = ^T;
	stop = ^S; susp = ^Z; time = 0; werase = ^W;
```

**Comment by McDutchie** [comment]
For the historical record, it looks like this bug was fixed in ksh 93u+m as a fortunate side effect of https://github.com/ksh93/ksh/commit/970069a6feb71424f4a98b9f3005181eeaa1c448 which backports two Red Hat patches. (Sure enough, the CentOS (Red Hat) version of 93u+ doesn't have the bug either, whereas the Debian version of 93u+ does.)
