### ISSUE TITLE
Test failure: API/misc/debug

### ISSUE THREAD

**Issue by floppym** [att/ast#1390]
**Description of problem:**
The API/misc/debug test fails on Gentoo Linux.

**Ksh version:**
2020.0.0-beta1

[system-info.txt](https://github.com/att/ast/files/3563565/system-info.txt)

```
 21/287 API/misc/debug                          FAIL     0.13 s (exit status 1)

--- command ---
/bin/sh /x/portage/app-shells/ksh-2020.0.0_beta1/work/ksh-2020.0.0-beta1/src/lib/libast/tests/run_test.sh src/lib/libast/tests/misc/debug /x/portage/app-shells/ksh-2020.0.0_beta1/work/ksh-2020.0.0-beta1/src/lib/libast/tests/misc
--- stdout ---
<I> run_test[69]: TEST_DIR=/x/portage/app-shells/ksh-2020.0.0_beta1/temp/api.debug.0KDbVg
--- stderr ---
<E> run_test[116]: Stderr for debug had unexpected differences:
--- /x/portage/app-shells/ksh-2020.0.0_beta1/work/ksh-2020.0.0-beta1/src/lib/libast/tests/misc/debug.err        2019-08-30 08:32:36.000000000 -0400
+++ debug.err   2019-09-01 10:05:08.106623197 -0400
@@ -2,16 +2,16 @@
 -p 666
 addr2info(): hello unit test
 ### 666 Function backtrace:
-1   test_backtrace + 0
-2   main + 0
+1   __libc_start_main + 0
+2   (null) + 0
 ### 666 Function backtrace:
-1   test_backtrace + 0
-2   main + 0
+1   __libc_start_main + 0
+2   (null) + 0
 ### 666 Function backtrace:
-1   test_backtrace + 0
-2   main + 0
+1   __libc_start_main + 0
+2   (null) + 0
 ### 666 Function backtrace:
-1   test_backtrace + 0
-2   main + 0
+1   __libc_start_main + 0
+2   (null) + 0
 ### 666   0.000 debug.c:987                   main() 01234567890123456789012...
 ### 666   0.000 debug.c:987                   main() 0123456789012...

```

**Comment by floppym** [comment]
This seems to be triggered by running meson configure with `CFLAGS="-O2"` set in the environment.
```
CFLAGS="-O2" meson build
```

**Comment by krader1961** [comment]
The problem is that enabling optimizations enables features like function inlining and eliding frame pointers. All of which will affect the backtrace provided by the libc `backtrace()` function.  The same problem occurs if you use the preferred way to enable an optimized build: `meson --buildtype=release`. From the [meson docs](https://mesonbuild.com/Reference-tables.html#compiler-and-linker-flag-environment-variables) where it talks about the use of env vars like `CFLAGS`:

> It is recommended that you do not use these. They are provided purely to for backwards compatibility with other build systems. There are many caveats to their use, especially when rebuilding the project. It is highly recommended that you use the command line arguments instead.

I've added a configure time check to skip that test if buildtype != debug. But I don't see anyway to do the same if you use `CFLAGS=-O2`.

**Comment by floppym** [comment]
> I've added a configure time check to skip that test if buildtype != debug. But I don't see anyway to do the same if you use CFLAGS=-O2.

That should work fine. Gentoo builds with buildtype = plain.
