### ISSUE TITLE
Regression with preceding variable assignments

### ISSUE THREAD

**Issue by McDutchie** [att/ast#1402]
**Description of problem:**
Commit 21023081 introduced a regression with variable assignments preceding ~~regular builtins that are~~ the `command` builtin when it is given an invalid option. Such assignments persist, though they shouldn't.

**Ksh version:**
Version A 2020.0.0-beta1-38-g21023081
Version A 2020.0.0-beta1-54-g9484249b

**How reproducible:**
Always

**Steps to reproduce:**
1. `ksh -c 't=ok; t=bug command -@; echo $t'`

**Actual results:**
`bug`

**Expected results:**
`ok`

**Additional info:**
n/a

**Comment by krader1961** [comment]
Good catch. Thanks, @McDutchie. This is because the `b_command()` implementation is weird. It can be invoked with `argc` == zero. Which I had to explicitly deal with:

https://github.com/att/ast/blob/9484249bcafaaab5e96c10d71905281f4acc296f/src/cmd/ksh93/bltins/command.c#L49-L54

What I failed to notice was this oddity:

https://github.com/att/ast/blob/d0d07c686a4b07afeb4e00bf87edf51df7f48969/src/cmd/ksh93/bltins/command.c#L74-L78

Specifically the test if `argc` == zero when an unrecognized flag is seen. The only other special builtin which is unusual in this regard is `b_kill()` which does `shp->sigval = 0;` before issuing an error and returning.

So the fix is trivial. I'll also add a regression test.
