### ISSUE TITLE
Abort in 'trap' builtin on invalid signal

### ISSUE THREAD

**Issue by McDutchie** [att/ast#1403]
**Description of problem:**
An invalid signal name starting with X, Y or Z causes the `trap` builtin to throw a segfault.

**Ksh version:**
Version A 2020.0.0-beta1-62-g66d09760

**How reproducible:**
Always

**Steps to reproduce:**
1. `for t in {A..Z}; do ../ksh93/ksh -c "trap - $t"; done`

**Actual results:**
The last three iterations throw segfaults.

**Expected results:**
No segfaults.

**Additional info:**
OS used: macOS 10.14.6, compiler: Apple LLVM version 10.0.1 (clang-1001.0.46.4)

```
### 25883 Function backtrace:
1   handle_sigsegv (in ksh) (fault.c:72)
2   _sigtramp (in libsystem_platform.dylib) + 29
3   ImageLoaderMachOCompressed::resolve(ImageLoader::LinkContext const&, char const*, unsigned char, long, ImageLoader const**, ImageLoaderMachOCompressed::LastLookup*, bool) (in dyld) + 263
4   sig_number (in ksh) (fault.c:809)
5   b_trap (in ksh) (trap.c:110)
6   sh_exec (in ksh) (xec.c:1293)
7   exfile (in ksh) (main.c:517)
8   sh_main (in ksh) (main.c:315)
9   main (in ksh) (pmain.c:39)
10  start (in libdyld.dylib) + 1
11  0x00000003 (in ksh)
Abort trap: 6
```

**Comment by krader1961** [comment]
The failure is due to a change I made long ago to the definition of `shtab_signals[]`. Specifically, changing the last element from `{"", 0, NULL}` to the more idiomatic `{NULL, 0, NULL}`. I changed the obvious places that checked the "name" member to just check the pointer being NULL rather than that it pointed to an empty string. I overlooked the `sh_lookup()` function.

What's fascinating is that fixing that mistake caused me to notice the same bug here:

https://github.com/att/ast/blob/1c9e7ab8404a135586e2de089f0e0b4ffbfce8e2/src/cmd/ksh93/edit/pcomplete.c#L134-L140

That loop also checks for a NULL pointer whereas the table definition has `{"", 0}` as the sentinel entry. The person who wrote that loop also expected the idiomatic pattern of using a NULL pointer rather than a pointer to an empty string to mark the end of the table.

**Comment by krader1961** [comment]
In fact, all of the other uses of `Shtable_t` use `NULL` as the name/value pointer in the sentinel entry. I've also seen other places in the code that use a `""` string as the sentinel value. Obviously someone in the distant past thought that because the first structure member was a `char*` that meant pointing to an empty string was either required or clearer than using a `NULL` pointer. Hopefully they now know better.
