### ISSUE TITLE
What is the minimum C language standard we want to support

### ISSUE THREAD

**Issue by krader1961** [att/ast#145]
While implementing a PR for issue #144 the Travis OpenSUSE compiler complained that this was illegal because its default C language standard is apparently older than C99: `for (int x = 0, ...)`. Which means you can't declare vars in the for loop. There is no question we should drop support for pre-ANSI C compilers. I think it is reasonable to also require support for the C99 language standard (aka ISO/IEC 9899:1999). Given that we do want to be able to build `ksh` on old operating systems like RHEL 5 I don't think we should require C11 (aka ISO/IEC 9899:2011). Especially since the more notable aspects of C11, such as improved support for threads, is not applicable to ksh.

**Comment by siteshwar** [comment]
C99 sounds like a good option.

**Comment by dannyweldon** [comment]
I'm inclined to agree.

**Comment by krader1961** [comment]
I'd like to swear because adding `--std=c99` causes failures like this:

```
FAILED: src/lib/libast/ast@sha/comp_resolvepath.c.o 
ccache cc  -Isrc/lib/libast/ast@sha -Isrc/lib/libast -I../src/lib/libast -Isrc/lib/libast/tm -I../src/lib/libast/tm -Isrc/lib/libast/vmalloc -I../src/lib/libast/vmalloc -I../src/lib/libast/std -Isrc/lib/libast/misc -I../src/lib/libast/misc -Isrc/lib/libast/string -I../src/lib/libast/string -Isrc/lib/libast/port -I../src/lib/libast/port -Isrc/lib/libast/path -I../src/lib/libast/path -Isrc/lib/libast/sfio -I../src/lib/libast/sfio -Isrc/lib/libast/comp -I../src/lib/libast/comp -Isrc/lib/libast/cdt -I../src/lib/libast/cdt -Isrc/lib/libast/aso -I../src/lib/libast/aso -I../src/lib/libast/features -I../src/lib/libast/include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -O0 -g --std=c99 -D_PACKAGE_ast -DMESON_BUILD=1 -Wno-unknown-pragmas '-DHOSTTYPE="linux.i386-64"' -fno-strict-aliasing -Wno-unknown-pragmas -Wno-missing-braces -Wno-unused-result -Wno-return-type -Wno-int-to-pointer-cast -Wno-parentheses -Wno-unused -Wno-unused-but-set-variable -Wno-cpp -Wno-char-subscripts -fPIC -D_BLD_ast -D_API_ast=20130625 -MMD -MQ 'src/lib/libast/ast@sha/comp_resolvepath.c.o' -MF 'src/lib/libast/ast@sha/comp_resolvepath.c.o.d' -o 'src/lib/libast/ast@sha/comp_resolvepath.c.o' -c ../src/lib/libast/comp/resolvepath.c
../src/lib/libast/comp/resolvepath.c:47:22: error: 'AT_FDCWD' undeclared (first use in this function); did you mean '_mac_AT_FDCWD'?
  return (s = pathdev(AT_FDCWD, file, path, size, PATH_PHYSICAL|PATH_ABSOLUTE|PATH_DOTDOT|PATH_EXISTS, NiL)) ? (s - path) : -1;
                      ^~~~~~~~
                      _mac_AT_FDCWD
../src/lib/libast/comp/resolvepath.c:47:22: note: each undeclared identifier is reported only once for each function it appears in
```

WTF? That suggests that the pre-C99 standard allows that symbol to default to zero.

**Comment by krader1961** [comment]
The problem is that the AST code seems to assume that if POSIX support is enabled (which happens if `--std=c99` is passed to the compiler) then all POSIX conformance levels are supported. But according to http://pubs.opengroup.org/onlinepubs/9699919799/ that isn't true. For example, `_SC_TRACE_NAME_MAX` is only defined in the 2001 standard:

> IEEE Std 1003.1-2001/Cor 2-2004, item XBD/TC2/D6/33 is applied, adding _SC_SS_REPL_MAX, _SC_TRACE_EVENT_NAME_MAX, _SC_TRACE_NAME_MAX, _SC_TRACE_SYS_MAX, and _SC_TRACE_USER_EVENT_MAX to the list of symbolic constants for sysconf().

But *src/lib/libast/comp/conf.tab* assumes any symbol tagged `POSIX` is available regardless of the level supported by the platform. On FreeBSD 11 only the 1992 standard is supported so those symbols aren't available:

```
#define _POSIX_VERSION         199212L
```

Whereas on macOS 10.13 it's

```
#define _POSIX_VERSION         200112L
```

Something similar is probably why `AT_FDCWD` isn't defined with the c99 standard in effect. TBD is how best to deal with this.

**Comment by krader1961** [comment]
It turns out that explicitly asking the compiler to use the C99 standard excludes a lot of features that would otherwise be enabled. Which is to say adding the `--std=c99` flag does not make that the minimum set of features supported. It makes C99 the strict set of features supported. Which is a problem because the ksh code depends on a lot of features not included in the C99 standard while at the same time trying to support compilers that don't support the C99 language standard.

Google "the wonderful thing about standards" for why this is a problem.

**Comment by kshji** [comment]
This is not answer for your problem. This is only memories how I can feel your feelings to try make "compatible" C code in hash of compilers with hash of standards.

I hate standards which are not compatible (=include) with old standards. If you crash old, new must be so much better that we accept cost of changes for old working codes. If it is only for look nicer are not reason to make crash for older envs.
Ex. for (int x = 0, ...)
Why I have to declare variable in using location ? Why not using syntax which are usable in "every" envs ?
I have not coded using C in long time. When I done it, I use lint and look warnings in every platform. After warnings were 0 with some define patterns in every our customers platforms, I accepted my macro layered code. That's was my lazy method to make compatible C for different envs. Then my test pattern maybe worked in every envs. Or give segmentation violation .... and back to the pointers world. Yes: those codes included too much defined or not defined settings.  Long history of some programs include lot of marks from history, like ksh. All we like to support also those older envs which are still working and using dev something new.  C answer is define. But if you have nothing better, then define. Macros are  nicer methods to make compatible code => result: your code look like some version of C but it's only your layered language based on macros. C is macro layered C.

My oldest server has started 1995 and still working and rebooting works, but security updating not working anymore :(. I'm not waiting that newest ksh is possible to build on that system ... even that C-compiler include flag GCC to be gcc compatible also. 

Have Google standards (macros) for C ? Then easiest way is to support it ?

Effort for all of you updating/cleaning/rewriting ksh code for todays dev envs,
Forked 1961, sh user since 1983.

**Comment by krader1961** [comment]
FWIW, It turns out that adding `-std=gnu99` (rather than `-std=c99`) enables support for the C99 language standard on old versions of gcc without limiting the available APIs. This allows using constructs like `for (int x = 0; x; x++)` without limiting the APIs we have access to. This seems to work fine on all the systems I've been using for testing including two BSD variants and several Linux variants.
