### ISSUE TITLE
Unable to get a restricted shell

### ISSUE THREAD

**Issue by aweeraman** [att/ast#1459]
**Description of problem:**
Unable to get a restricted shell with 2020.0.0

**Ksh version:**
2020.0.0

**How reproducible:**
Consistently with a fresh build from master with this tree: https://github.com/att/ast/tree/2f06a34e737cb2a0d8c1a052d97924ad27e445e0

**Steps to reproduce:**
meson build
ninja -C build
cd build/src/cmd/ksh93/
ln -s ksh rksh
./rksh
export PATH=/sbin <-- this executes without an error

**Actual results:**
Able to execute actions which should be restricted in rksh

**Expected results:**
./rksh: PATH: restricted

**Additional info:**
Linux ninsei 5.3.0-7625-generic #27~1576337002~19.10~bc3488b-Ubuntu SMP Sat Dec 14 18:31:03 UTC  x86_64 x86_64 x86_64 GNU/Linux

**Comment by krader1961** [comment]
Yes, this appears to be broken. But it's also broken in the ksh93v- code from the old AST team we used as a starting point:

```
$ ln -s /usr/local/bin/ksh93v rksh
$ ./rksh
KSH PROMPT:1: echo $KSH_VERSION
Version ABIJM 93v- 2014-12-24
KSH PROMPT:2: export PATH=/sbin
```

Doing the same thing with the ksh93u+ binary produces the expected error.

**Comment by krader1961** [comment]
Also, there are quite a few unit tests of restricted shell behavior. Why aren't they failing? Is this specific failure mode (i.e., assigning to `PATH`) unique among the restricted behaviors and untested?

**Comment by aweeraman** [comment]
Yeah, restricted.sh seems to execute successfully, which was a little strange.

What I just observed was that the restricted.sh uses -c to pass in the command and validate the error:
LC_MESSAGES=C rksh -c "$@" 2> out > /dev/null

and when I do the same, it seems to work:
~/ast/build/src/cmd/ksh93$ ./rksh -c "export PATH=/sbin"
./rksh: PATH: restricted

But not interactively:
~ast/build/src/cmd/ksh93$ ./rksh
~/ast/build/src/cmd/ksh93 [182]$ export PATH=/sbin
~/ast/build/src/cmd/ksh93 [183]$

**Comment by krader1961** [comment]
This bug was introduced in the ksh93v- source here:

https://github.com/att/ast/blob/e770c77e9816e156c6df4a455e71b5f9fff79310/src/cmd/ksh93/edit/edit.c#L761-L768

The `sh_isoption(shp,SH_RESTRICTED);` should be `sh_onoption(shp,SH_RESTRICTED);`. None of that manipulation of option `SH_RESTRICTED` exists in the ksh93u+ source. That version of the code unconditionally ran the `sh_trap(".sh.subscript=$(tput cuu1 2>/dev/null)",0);`.

One might think that this change is because manipulating compound var `.sh.subscript` should be allowed while a restricted shell is initializing. That, however, is wrong. The reason for this incorrect change after the ksh93u+ release is to allow the `2>/dev/null` which is otherwise disallowed by a restricted shell. Apparently someone reported the `rksh: line 1: /dev/null: restricted` error they saw when running a restricted ksh93u+ interactive shell and the old AST team "fixed" it without actually testing their fix.

**Comment by krader1961** [comment]
@aweeraman I'm curious what caused you to notice this bug. Mostly because I would expect use of the restricted shell feature to be rare these days since it doesn't really provide much security.

**Comment by aweeraman** [comment]
That explains the issue!

We're including rksh in the Debian binary and I happened to test it and so noticed it while comparing with 93u+20120801.

If you have a patch available, I'd be happy to cherry pick it and push out an update.

**Comment by aweeraman** [comment]
Thank you, that works like a charm. Including this patch in the next Debian update.

**Comment by krader1961** [comment]
@aweeraman Note that the change to the master branch won't apply cleanly to the 2020.0.0 release. If you can't wait for a 2020.0.1 release you should cherry-pick all the fixes in the 2020.0.1 branch; not just the fix for this issue.

**Comment by aweeraman** [comment]
@krader1961 do you have any plans of releasing 2020.0.1 anytime soon?

**Comment by krader1961** [comment]
@aweeraman It's been three months since the 2020.0.0 release and we have  fixes for four bugs. Although, only this one is likely to be noticed by an appreciable number of people. I think we should make a 2020.0.1 release soon; certainly no later than three months hence (six months after 2020.0.0 was released). The decision is ultimately up to @siteshwar. He works for Redhat and has far more experience dealing with ksh releases on Linux.

**Comment by jelmd** [comment]
@aweeraman Note that this is a hijacked repo and neither krader nor siteshwar have obviously any experience in software maintenance as e.g. the intended versioning shows (which they try to sell as semantic versioning). Be very carefully in what [crap] you are adding to debian. krader1961 does not even know ksh93 - IMHO he is just a C hacker, who has too much time ...
