### ISSUE TITLE
"cannot execute [Exec format error]" on cygwin64

### ISSUE THREAD

**Issue by brano-tichy** [att/ast#1474]
ksh93u+ (`Version AJM 93u+ 2012-08-01`) compiled from source on cygwin64
`CYGWIN_NT-10.0 WSHQ1803 3.1.4(0.340/5/3) 2020-02-19 08:49 x86_64 Cygwin`
behaves exactly like bug described in RELEASE:

> 08-12-07  A timing bug on some systems (for example darwin), that could
> 	  cause the last process of a pipeline entered interactively to fail
> 	  with an "Exec format error" has been fixed. 

the error code is 126
setting `CCFLAGS=-D_AST_no_spawnveg=1` helped

also `lib\libast\path\pathnative.c` relies on `cygwin_conv_to_win32_path` which is not supplied, i had it replaced with `cygwin_conv_path`

**Comment by jghub** [comment]
@brano-tichy:
FYI, the att/ast team is not actively developing/maintaining ksh93. but it has recently rewound this repo to ksh93u+ since previous development by external committers in the last 2-3 years had led to an undesirable situation. background is in #1466 and #1464 (and elsewhere in the issue history...).

however a community initiative has just started (a couple of weeks ago) to maintain and possibly improve ksh93u+ in the future. so you might post your ksh93u+ issues here in the future: https://github.com/ksh-community/ksh

**Comment by brano-tichy** [comment]
thanks for the heads-up, i posted the issue there.
