### ISSUE TITLE
Investigate issues identified by the `bin/lint` command

### ISSUE THREAD

**Issue by siteshwar** [att/ast#161]
To run the build through ```clang-analyzer``` :

```
ninja scan-build
```

Currently there are more than 250 bugs that are identified by it.

**Comment by krader1961** [comment]
This makes me so sad as I love ksh. On the other hand, only ~250 bugs? Heck we should be able to fix that many bugs in a few days. :smile:

On a more serious note this is why I want to make it trivial and routine to run the code through tools like `clang-format`, `oclint`, `cppcheck`, and `scan-build`. There should be zero warnings from the compiler or any of those tools. Let alone obvious errors being identified.

**Comment by krader1961** [comment]
My PR#368 enables clang static analysis (what `ninja scan-build` does) as part of running `oclint`. As well as running the code through `cppcheck`. Just the *src/cmd/ksh93* code produces a report that is over 7000 lines long.

**Comment by krader1961** [comment]
I'm closing this because it is now trivial to lint the code, including just the files in an uncommitted change or the most recently committed change. Simply type `bin/lint` or `bin/lint all`. There is no point keeping this issue open because there will always be lint warnings and errors. Which means this issue will never be closed.
