### ISSUE TITLE
local keyword is not recognized in a function

### ISSUE THREAD

**Issue by siteshwar** [att/ast#220]
Rerpoducer script:

```
test_func() {
    local stat=$(< /proc/self/stat)
    echo $stat
}

test_func
```

Running this script gives this error :

```
 local: local can only be used in a function
```

**Comment by dannyweldon** [comment]
Interestingly, it works correctly if the function is defined using the `function` keyword.

**Comment by deekej** [comment]
By the way, one more thing I'm seeing (ksh-20120801-31 version in Fedora 25):

```ksh
$ cat ./test.ksh 
#!/bin/ksh

function func {
  local stat=($(< /proc/self/stat))
  echo $stat
}

func

exit 0
```
Results in:
`./test.ksh: syntax error at line 4: `(' unexpected`

However, changing the script like this:
```
#!/bin/ksh

function func {
  stat=($(< /proc/self/stat))
  echo $stat
  unset stat
}

func

exit 0
```

Will work OK - for example:
```
$ ./test.ksh
6785
```

**Comment by dannyweldon** [comment]
Hmm, I'm also seeing no output when running just:

    echo $(</proc/self/stat)

**Comment by krader1961** [comment]
Note that this issue seems to be predicated on the `SHOPT_BASH` symbol. Which is being discussed in issue #238 for removal. The state of the ksh source code at this time which  implements the `local` keyword is obviously incomplete and/or broken with  respect to this feature.

**Comment by hlangeveld** [comment]
IIRC The AST group subscribed strongly to the idea of one interface, one name, one behaviour. When introducing new behaviour they would go out of their way to create a new interface with a new name.

From what I remember when `typeset` was introduced, the `function` keyword was created precisely for supporting local variables.  The AST group did not want to "contaminate" old  `sh` style functions with different behaviour, so a new type of function was created.

**Comment by colstrom** [comment]
@hlangeveld This is consistent with my understanding as well. `func()`-style functions behave as `sh`, `function func`-style functions support things like `local`.

**Comment by bk2204** [comment]
I'll point out a few things about the `local` keyword:

1. There's a request to the Austin Group (the POSIX folks) about standardizing it as part of POSIX which has garnered a lot of comments in favor. `ksh` has typically been capable of running POSIX commands, so it may be worthwhile to implement for that reason.
1. Debian requires all shells that can be used as `/bin/sh` to implement `local` (and they don't build with `SHOPT_BASH`). Consequently, it isn't possible to use `ksh` as `/bin/sh` on a Debian or Ubuntu system.
1. Git requires a shell providing `local` in order to run the testsuite and shell commands. Consequently, it isn't possible to use `ksh` as the shell for Git.
1. All other open source POSIX-compliant shells that I'm aware of implement `local`: `bash`, `dash`, `mksh`, `pdksh` (and derivatives, like OpenBSD's `ksh`), and `zsh`.

The first three would necessitate an implementation _outside_ of `SHOPT_BASH`. Now, nothing _requires_ that `ksh` fit these niches; it may be that folks prefer to preserve historical behavior over adding `local`, and that's fine. But if there's a desire to fill these use cases, then `local` should probably be implemented as a standard feature.

**Comment by dannyweldon** [comment]
I am in favour of having `local` as a standard builtin.  It might be worth checking if it breaks scripts that have `local` defined as an alias like this, but it should be okay:

```ksh
alias local=typeset
```

**Comment by krader1961** [comment]
Note that `local` is defined as a builtin alias for `typeset` here:

https://github.com/att/ast/blob/856e0956d7b455398fefb870a669c7d092bad017/src/cmd/ksh93/data/builtins.c#L69-L72

What do people think about also making `declare` an explicit alias for `typeset`?

Note that the use of `BLT_SPC` in the definition of `declare` means it cannot be overridden by a function (and possibly other things) whereas `local` can. Whether the definition of `local` should also include `BLT_SPC` is unclear.

**Comment by krader1961** [comment]
Note that due to how the builtin definitions interact with the `alias` command you can override even `typeset` with an alias that does not invoke the builtin of the same name. Whether that is a feature or bug is open for debate. :smile: This means that adding `local` as a builtin without regard to whether ksh was built with `SHOPT_BASH` set to true does not affect something like `alias local=typeset` or `alias local='echo WTF '.

**Comment by krader1961** [comment]
Note: the `local` command doesn't exist in the ksh93u+ release. It was added after that release as part of the (bogus, IMHO) attempt to implement a bash emulation mode. I'm happy to see new behaviors implemented such as `local` being an alias for `typeset`. But that should be done because it is generally useful, not in a misguided attempt to emulate the behavior of a different shell and only if that emulation is turned one (e.g., by being invoked as */bin/bash*).

**Comment by krader1961** [comment]
Also, the `declare` and `local` commands only depend on the shell being built with the `SHOPT_BASH` preprocessor symbol being "true". Whereas other behaviors involving that symbol also depend on the program being invoked as "bash". Personally, I think those two aliases for `typeset` should be enabled unconditionally. Whether that can be done in the post ksh93u+ release is an open question. The AST team seemed to think the answer is "yes" since they made that behavior the default in the ksh93v- release whereas in the ksh93u+ release the answer was "no".

**Comment by krader1961** [comment]
I just noticed that */etc/profile* on WSL (Windows Subsystem for Linux) assumes the shell supports the `local` command. I'm going to just enable `local` and `declare`. The risk of causing problems for existing ksh scripts seems so negligible that it isn't worth worrying about. Clearly the AST team felt the same since they intended ksh be built with `SHOPT_BASH` set true.

**Comment by dannyweldon** [comment]
> I'm going to just enable local and declare.

Sounds good to me.  One thing to be aware of though is that in `bash`, `local` will only work inside a function.  Using it outside a function gives this error:

`bash: local: can only be used in a function`

Having a `local` builtin which checks this before calling `typedef` would make it more compatible, but whether the behaviour of `bash` is conceptually correct or desirable is another matter.  I just checked and `dash` does the same thing, but `zsh` 5.1.1 doesn't seem to care, not that it cares for standards.

**Comment by krader1961** [comment]
The AST team who implemented `local` already ensured it is only usable inside a function:

https://github.com/att/ast/blob/da398b64e1e3babfb2c821206a93fb40218f0b2e/src/cmd/ksh93/bltins/typeset.c#L409-L414

```
KSH PROMPT:1: local wtf
src/cmd/ksh93/ksh: local: local can only be used in a function
```

Whether or not that test is 100% correct is TBD.

**Comment by krader1961** [comment]
I just noticed a bug in the existing code. Notice this definition:

https://github.com/att/ast/blob/014e9086b7d90c7661b4ce252d2c98c16ecbf227/src/cmd/ksh93/include/builtins.h#L43-L47

That corresponds to an offset in `shtab_builtins[]`. The problem is that `declare` is at offset 17 and `local` is at offset 18 in that table:

https://github.com/att/ast/blob/014e9086b7d90c7661b4ce252d2c98c16ecbf227/src/cmd/ksh93/data/builtins.c#L51-L72

`SYSLOCAL` is only used two places. It's not clear what the ramifications are of this bug.
