### ISSUE TITLE
Core dumps under Arch Linux with latest commits (17ae556)

### ISSUE THREAD

**Issue by Head-on-a-Stick** [att/ast#249]
I am running Arch Linux (with the [Testing] repositories enabled) and I'm using the latest version of ksh93 built from this AUR package:

https://aur.archlinux.org/packages/ksh93-git/

As of the most recent commits (~10 hours ago), I am seeing recurrent core dumps of ksh93.

Managed to catch one in gdb just now:

https://gist.github.com/Head-on-a-Stick/e5d34aedb5c9159b79535faf8a6bb588

I'm not sure how to build an unstripped version with the debugging symbols enabled, sorry.

The versions built from the  20th December (and earlier) did not suffer from this.

**Comment by siteshwar** [comment]
It may be related to this commit f4ffb168a9591a6276c3c8a9e127a169ec641b45

Would it be possible for you to check if reverting this commit fixes the problem ?

**Comment by Head-on-a-Stick** [comment]
OK, I've build a new version without those changes and I'll switch back to ksh93 as the login shell and see if it dumps again.

I will report back soon.

Thanks!

**Comment by Head-on-a-Stick** [comment]
2 hours in and no errors so far, I think that may have been it; the unchanged version was crashing pretty quickly before.

I will keep using this version for a while and post again if it happens again.

**Comment by krader1961** [comment]
Commit f4ffb16 doesn't change the code. It simply reinstates the original logic to use `utimensat()` if the platform provides it, else `utimets()` if that is available, else `utimes()`. Since Arch Linux is based on GNU Linux, and therefore should provide a `utimensat()` implementation, that commit should not have made any difference for anyone building ksh on Arch Linux. That commit only affects whether ksh can be built on non GNU Linux platforms.

However, the `#include <sys/time.h>` used to probe for that syscall might be incorrect since on most (all?) Linux systems that should be `#include <time.h>`. Why that discrepancy doesn't cause a failure in the Travis test environments or my Linux VMs is TBD.

P.S., The only time I attempted to install Arch Linux under VMware I gave up. So I'm going to be poking around in the dark

**Comment by Head-on-a-Stick** [comment]
@krader1961, you can use Manjaro or Antergos with my binary package if you want to test this quickly in a VM:

https://download.opensuse.org/repositories/home:/Head_on_a_Stick:/Arch/Arch_Extra/x86_64/ksh93-2014.12.24-10-x86_64.pkg.tar.xz

I have also reproduced this problem in Debian stable ("stretch") but the project will only build in that distribution if the meson version from the stretch-backports repository is used.

Reversing the suggested commit does seem to fix the problem in Arch but I will continue to test today and I will also try that change in Debian stable.

**Comment by Head-on-a-Stick** [comment]
@krader1961 wrote:
> Linux systems that should be `#include <time.h>`.

I've just tried rebuilding the package with <time.h> in place of <sys/time.h> and the shell still fails repeatedly after only a few moments of use.

Also, to clarify my previous comment:

> Arch Linux also only has `utimes()`

Having read up a bit I can see that obviously the Linux kernel has had utimensat() since 2.6.22 but meson *claims* that it cannot find any such function, hopefully my previously attached log will clarify this.

**Comment by Head-on-a-Stick** [comment]
(Apologies for spamming the thread)

More information: the shell crashes after almost exactly 570 seconds, this is very repeatable.

I found the debugging tips on the wiki and rebuilt the package with '-o0 -ggdb3' & the register keyword disabled and obtained this `bt full` output from gdb:

https://gist.github.com/Head-on-a-Stick/df126f498c80f6843e37353bb5ed7eb6

**Comment by krader1961** [comment]
I have no idea why I thought the `utimensat()` and `utimets()` functions were defined in the *sys/time.h* header. They're actually defined in the *sys/stat.h* header.

To illustrate how hard these checks are to accommodate all platforms we care about consider that even with my fix to the included header this still fails to detect `utimensat()` is valid on macOS 10.13 even though it provides that function:

```
ld: weak import of symbol '_utimensat' not supported because of option: -no_weak_imports for architecture x86_64
```

In some sense this is reasonable since you might reasonably expect a ksh binary built on macOS 10.13 to also work on 10.12. Dealing with evolving APIs is a major PITA.

Also, thanks for the backtraces, @Head-on-a-Stick. Looking at the implicated code it is clear the code that is run when `utimensat()` and `utimets()` are not available does not correctly handle the `av` parameter being `NULL`. This is a case of code bit-rot which wasn't noticed before my (incorrect) feature detection change because that block of code isn't normally enabled.

**Comment by krader1961** [comment]
@Head-on-a-Stick, If my commit doesn't fix this failure on your distro please reopen this issue or open a new issue. My commit should fix the detection of the `utimensat()` function and thus avoid the bug in the code that is used if that function is not available.
