### ISSUE TITLE
clang_format status

### ISSUE THREAD

**Issue by catull** [att/ast#256]
@krader1961 @siteshwar 
How is the mass-reformatting going along?
A few words would be great, thanks.

**Comment by krader1961** [comment]
I'm currently stalled due to the time required to respond to the other issues and PRs. Which is a good thing :smile: Having said that I would prefer that no one else restyle (or reformat) the the code since there is a lot that clang-format doesn't do. Most notably involving adding/removing braces where that is needed. Which wouldn't be a big deal in most projects but in this project it is a big deal given how many instances there are of patterns like this:

```
if (something)
    do_something();
else
    do_something_else();
```

I want the code in a consistent style before others worry about its style. Even more important than that is a command for automating the styling rules. In the Fish shell I did this via `make style` and `make style-all` commands. We'll probably do something slightly different here since we're using Meson rather than GNU autoconf.

**Comment by catull** [comment]
I am not thinking of style, nor am I doing anything along the lines.
Thanks for the heads-up.

As as side-note, I am a supporter of "blocks need curly braces, even for a single line"; be it while-, for- or if-blocks.
Every formatter I have come across can add extra curly braces.

I won't get in your way.

**Comment by krader1961** [comment]
There is a LLVM/clang based tool (whose name I don't recall) which will add/remove braces. But it had problems and was not widely adopted when I looked at it a couple of years ago. The `clang_format` tool on the other hand is mature, conservative, and safe to use. After 3+ decades of programming in C I have come the the conclusion that braces can only be safely omitted from if/for/while statements if the predicated block is a single statement that fits on the same line as the if/for/while statement (given the line length limits of the project).
