### ISSUE TITLE
Test on builtins fail under macOS - investigation

### ISSUE THREAD

**Issue by catull** [att/ast#262]
# Problem

The test `builtins` fails, because the shared library libast.dylib cannot be found.

The test displays these lines, when run with `meson test -v builtins`:
```log
...
dyld: Library not loaded: @rpath/libast.dylib
  Referenced from: ast.git/build/src/cmd/ksh93/ksh
  Reason: image not found
...
```

No other test fails this way.
Which means none of the other tests require to dynamically access types/functions defined in any of the 3 shared libraries.

`otool -L ksh` reports:

```log
ksh:
	@rpath/libast.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libcmd.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libcoshell.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.60.2)
	/usr/local/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
```

# Two solutions
## Solution 1 (terrible)

One way that the test succeed is ... when I copy the 3 .shared library files to /usr/local/lib.

The test succeeds whether the variables {DY}LD_LIBRARY_PATH are set or not.

## Solution 2 (much better)

The trick is to assist the running shell and the OS to find the 3 shared libraries in development.
The magic environment variable is DYLD_FALLBACK_LIBRARY_PATH, currently I am in the build folder of the source tree.

```shell
export DYLD_FALLBACK_LIBRARY_PATH=src/lib
```

# Consideration

Setting DYLD_LIBRARY_PATH should not be used outside of development.
I never set it, never have had the need to.

**Comment by krader1961** [comment]
Note that we are explicitly not supporting  dynamically loaded libraries during this transition period to a new build system:

```
src/cmd/ksh93/meson.build:# TODO: Add '-DSHOPT_DYNAMIC' when we have figured out how to get Meson to
```

So while mechanisms like exporting a `DYLD_FALLBACK_LIBRARY_PATH` var might help reduce failures on macOS it's not clear we want to do so long term. Unless, of course, implementing `-DSHOPT_DYNAMIC` is not sufficient to fix this issue.

**Comment by catull** [comment]
I am afraid I cannot follow.

Are you suggesting the fix above is in or out ?

The special env variable is only needed in development at the moment.
I have shown that if the shared library is installed in /usr/local/lib, there is no need to have that special env variable.

As we move on, I will re-examine the need for this variable _in development_; as soon as we have no need for it, it goes away.

**Comment by krader1961** [comment]
This [stackoverlow question](https://stackoverflow.com/questions/3146274/is-it-ok-to-use-dyld-library-path-on-mac-os-x-and-whats-the-dynamic-library-s) sheds some light on the matter. As does running `man dyld` on my macOS system.

I see that your change has nothing to do with support for dynamically loaded libraries in the sense of my earlier comment. However, I don't understand why you're using `DYLD_FALLBACK_LIBRARY_PATH ` rather than `DYLD_LIBRARY_PATH`. That latter seems to be the more appropriate env var for this situation. We do not want the macOS dynamic linker to use an already installed version of these libraries. We want it to use the library built from the current source code.

Your change also deviates from how `LD_LIBRARY_PATH` is set for non macOS distros. That seems wrong to me. Shouldn't the change be

```
   ld_library_path = 'DYLD_LIBRARY_PATH=' + ':'.join(
       [libast_build_dir, libcmd_build_dir, libcoshell_build_dir])
```

rather than

```
ld_library_path = 'DYLD_LIBRARY_PATH=src/lib'
```

Also, I'm not seeing the `builtins` test failure you're seeing. I have tested this on macOS 10.12 (Sierra) and 10.13 (High Sierra). That is surprising since I would expect to see the same test failures you are are seeing.

**Comment by catull** [comment]
> Shouldn't the change be
>```meson
>ld_library_path = 'DYLD_LIBRARY_PATH=' + ':'.join(
>       [libast_build_dir, libcmd_build_dir, libcoshell_build_dir])
>```

Yes, that does work as well.
But DYLD_FALLBACK_LIBRARY_PATH works in a node-manner, meaning that any directory defined in it is going to be searched recursively to find the shared library.
Your suggestion is more strict, I have nothing against strictness.

May I remind you that `man dyld` mentions this:

```man
DYLD_FALLBACK_LIBRARY_PATH
      This  is a colon separated list of directories that contain libraries.  It is used as the default location for libraries not found
      in their install path.  By default, it is set to $(HOME)/lib:/usr/local/lib:/lib:/usr/lib.
```

This means that if you are not going to set it to something else, once you have /usr/local/lib/libast.dylib installed, this version of the library is interfering with any tests.
This statement is made without any proof.

**Comment by catull** [comment]
I feel embarassed now.
I pulled in the latest changes from master, cleared all changes.
Then I did the usual meson and ninja steps.
Now the builtins runs without any extra configurations; also, the shared libraries are not installed anywhere.

Case closed.

**Comment by krader1961** [comment]
> Can we rename the tests, replace the parentheses with a simple '-'?

That's fine by me. Especially since I use fish as my interactive shell and parens signal command substitution; i.e., `(cat a_file)` in fish is equivalent to `$(cat a_file)` in POSIX shells.

I ran the following which shows that the right libraries are used when running the built, but uninstalled, ksh binary so for the moment there doesn't seem to be any changes needed to the build/test process:

```
env DYLD_PRINT_RPATHS=1 src/cmd/ksh93/ksh                                                                                                 13 ms
RPATH successful expansion of @rpath/libast.dylib to: /Users/krader/projects/3rd-party/ast/build/src/lib/libast/libast.dylib
RPATH failed to expanding     @rpath/libcmd.dylib to: /Users/krader/projects/3rd-party/ast/build/src/lib/libast/libcmd.dylib
RPATH successful expansion of @rpath/libcmd.dylib to: /Users/krader/projects/3rd-party/ast/build/src/lib/libcmd/libcmd.dylib
RPATH failed to expanding     @rpath/libcoshell.dylib to: /Users/krader/projects/3rd-party/ast/build/src/lib/libast/libcoshell.dylib
RPATH failed to expanding     @rpath/libcoshell.dylib to: /Users/krader/projects/3rd-party/ast/build/src/lib/libcmd/libcoshell.dylib
RPATH successful expansion of @rpath/libcoshell.dylib to: /Users/krader/projects/3rd-party/ast/build/src/lib/libcoshell/libcoshell.dylib
$
```

So closing for now.

**Comment by catull** [comment]
The reason why I suggest renaming case(VARIANT) to to case-VARIANT is that I always have to either place them
- in single quotes  'case(VARIANT)'
- in quoted parentheses   case\\(VARIANT\\)

Double quotes ain't helping.

But I do forget here and there ...
