### ISSUE TITLE
man sh.1 not include json print and printf, test pattern also not include full json testing

### ISSUE THREAD

**Issue by kshji** [att/ast#27]
sh.1 not include print -j and printf %(json)B extensions.

RELEASE:14-07-15  Fixed a bug in which json format output with 'print -j' had a comma
RELEASE:13-05-28 +Added -j option to print (and %(json)B format specifier to printf)
RELEASE:          which will print a compound shell variable in JSON format.

[ My example read and print json](https://github.com/kshji/ksh/blob/master/Sh/json.read.write.sh).

I think that **comvar.sh** test is not enough for print -j. Arrays should be part of the compound variable. Also printf should include json testing.

**Comment by krader1961** [comment]
See my comments on related issues #39 and #820. I initially argued to retain support for JSON because it seemed like a worthwhile enhancement. And I still think that is true. However, the current implementation is broken for both JSON input and output. And has unacceptable entanglement with the "namval" code (specifically in the *src/cmd/ksh93/sh/nvtree.c* module). Code which already has too many bugs independent from its support for JSON.

**Comment by siteshwar** [comment]
> I think that comvar.sh test is not enough for print -j. Arrays should be part of the compound variable. Also printf should include json testing.

You are correct that we don't have enough test cases for `json` support. Since current implementation for `json` support is broken, we are going to disable it in next release. In future if we choose to reintroduce this feature, it won't be done without test cases, so I am going to close this issue.
