### ISSUE TITLE
Please create tag(s)

### ISSUE THREAD

**Issue by ilovezfs** [att/ast#3]
In order to adopt the new GitHub repository as its upstream, the Homebrew formula will need a release tag that can be assigned to the stable spec. This allows a tarball of the tag to be downloaded from GitHub and the sha256 of the tarball to be recorded in the formula to ensure integrity.

Please see https://github.com/Homebrew/homebrew/pull/49653#issuecomment-191031130

**Comment by apjanke** [comment]
:+1: on this. Would be nice to have tagged releases so we can get these installations working again under Homebrew. (Affects `vmalloc` and `vcodex`, which were previously downloaded from the web site.) Would probably be convenient for other users, too, because then they could download distribution tarballs and install from them, instead of having to clone the Git repo.

**Comment by krader1961** [comment]
@ilovezfs and @apjanke: It's not clear what you're requesting. Is simply tagging commits that represent a new stable release sufficient for your needs? Should something like a `stable` tag always be attached to the current stable release or should we simply use a unique tag for each stable release and somehow communicate to Homebrew when a new stable release is available?

A couple of the maintainers (e.g., @siteshwar and myself) would like to rearrange this project to focus on ksh and shunt the non-ksh bits into a separate branch. At some point that will likely entail switching the build system from Nmake to Meson (or possibly Cmake). How does that affect Homebrew?

**Comment by siteshwar** [comment]
Closing due to lack of response from reporter. In any case, in future when we plan to make a release, we are going to definitely tag commits with version number.

**Comment by siteshwar** [comment]
We have created tags for previous releases https://github.com/att/ast/releases

**Comment by apjanke** [comment]
Thank you! I will look at re-pointing the Homebrew formula here and pulling in the new "93v" release.

**Comment by krader1961** [comment]
@apjanke I recommend you not pull the "93v" release. It is a beta release (it's really "93v-"). It is riddled with bugs. Many quite serious such as use-after-free bugs that can result in using the wrong data or the shell dying from a SIGSEGV. I've confirmed that none of the most blatant use-after-free bugs do not exist in the 93u release. We've fixed a lot of those bugs but some are still unresolved. And some of the fixes we've already made have less than 100% confidence the fix is entirely correct.

**Comment by apjanke** [comment]
Okay, I'll avoid. Thanks!

**Comment by krader1961** [comment]
We're slowly resolving the more obvious bugs in the new code. We recently enabled ASAN which has identified bugs we weren't previously aware of. Once all of those are dealt with and there are no serious [Coverity Scan issues](https://scan.coverity.com/projects/ksh?tab=overview) we'll probably be comfortable making a new release. Help from people interested in seeing a new release is welcomed.
