### ISSUE TITLE
Recently introduced macro redefinition SF_APPEND

### ISSUE THREAD

**Issue by catull** [att/ast#309]
A few days I ago, this warning appeared in compilations:
```
../src/lib/libast/include/sfio.h:194:9: warning: 'SF_APPEND' macro redefined [-Wmacro-redefined]
#define SF_APPEND       SF_APPENDWR     /* BSDI sys/stat.h              */
        ^
/usr/include/sys/stat.h:336:9: note: previous definition is here
#define SF_APPEND       0x00040000      /* writes to file may only append */
        ^
```

It appears 98 times.

**Comment by krader1961** [comment]
This was introduced by commit 0c1fad6, "Remove 'common' feature test from libast". The problem is that the removed *src/lib/libast/features/common* `iffe` test script had some special tests for things like macOS defining `SF_APPEND`. This type of problem is actually expected to occur since the first step in removing a dependency on `iffe` results in a static header file. As we build on various systems we'll then reintroduce additional feature tests.

In this case the `iffe` dynamically generated header includes `#define _mac_SF_APPEND 1` while the new static header does not. What is interesting is that symbol isn't even needed. It is sufficient to just do a `#ifdef SF_APPEND` where `_mac_SF_APPEND` is tested.

**Comment by catull** [comment]
Will change that accordingly.

What about the next 3 lines
```c
#if !_mac_SF_CLOSE
#define SF_CLOSE	SF_CLOSING	/* AIX sys/socket.h		*/
#endif
```

Do they need to become
```c
#ifdef SF_CLOSE
#define SF_CLOSE	SF_CLOSING	/* AIX sys/socket.h		*/
#endif
```
?

SF_CLOSE is not needed in any .c source files.
It is assigned conditionally in src/cmd/ksh93/include.io.h, which does include the header file sfio.h:
```c
#ifndef SF_CLOSING
#define SF_CLOSING	SF_CLOSE
#endif
```

**Comment by catull** [comment]
In the same header - io.h - the next lines are:
```c
#ifndef SF_APPENDWR
#define SF_APPENDWR	SF_APPEND
#endif
```

This is what I have found out.

In `ast-open.README` there is this change log entry:
```log
01-02-22 pathprobe: reprobe test now checks probe.ini too
	 sfio_s.h: advertize public Sfio_t members with _ prefix
	 sfio.h,features/stdio: add <sfio_s.h> reference
	 sfhdr.h: map <sfio_s.h> _foo to foo
	 sfio.h: SF_APPEND=>SF_APPENDWR, SF_CLOSE=>SF_CLOSING
```

This means that the old constant SF_APPEND was renamed to SF_APPENDWR, SF_CLOSE renamed to SF_CLOSING.

If a platform already defines SF_APPEND - most likely a BSD one - SF_APPEND is redefined with the value of SF_APPENDWR in sfio.h.
But in io.h, if SF_APPENDWR is NOT defined yet, it takes on the value of SF_APPEND.

On a platform that does not define SF_APPEND, no new SF_APPEND is created in sfio.h.
Only if SF_APPENDWR is not defined yet, it is newly introduced with the value of SF_APPEND.

Is there a slight chance that SF_APPEND may never be defined ?
It would cause SF_APPENDRW to #error out in io.h line 39, would it not ?

So far, we have not seen a compilation error.

I am hesitant to suggest that the passage above should be
```c
#if !defined(SF_APPENDWR) && defined(SF_APPEND)
#define SF_APPENDWR	SF_APPEND
#endif
```

**Comment by krader1961** [comment]
The safest fix is to mimic the original, `iffe` based, behavior. That is, wrap those `#define`s in `#ifndef` tests. We should be really hesitent about changing the logic of the libast code. Even if it looks self-evident the change is correct. That code is fragile. And I'm hoping we can remove the dependency on SFIO sooner rather than later. Thus allowing us to simply delete all that code.
