### ISSUE TITLE
Purpose of this repo: AST or ksh ?

### ISSUE THREAD

**Issue by catull** [att/ast#326]
When I see "att/ast", especially when I read the header
> This is the AT&T Software Technology ast software download site from AT&T Research.

My association is, "Look, this is AT&T Software Technology (AST) toolchest".

The toolchest contains many tools: ksh, nmake, coshell, probe etc.

Does this project still plan to revive all those tools ?

If it is only concentrating on ksh, are there plans to move the source code to https://github.com/att/ksh ?

That repo currently has a mini web-site.

Has this perhaps been discussed in the past ?

**Comment by krader1961** [comment]
> Does this project still plan to revive all those tools ?

No. Or rather no one who has been contributing changes is interested in maintaining the non-ksh code. And it is extremely hard to justify doing so since GNU, BSD, and other platforms provide good implementations for the non-ksh pieces of the AST toolchest. And none of those platforms is going to adopt the AST version of those tools. Consider the SFIO library: It would have been marvelous if the industry had adopted it as the successor to the stdio library. But that didn't happen and at this juncture the probability it will happen is vanishingly close to zero.

Or consider the Nmake build system. Yes, there are people and companies who may be using it. But I'll bet you $50 no one has adopted it for their own projects in the past decade. It's chock full of code to support things, like pre-ANSI C compilers, that is no longer relevant. And all of that code makes it extremely difficult to improve it. Any person or company choosing today between using Nmake, Cmake, or Meson will never choose Nmake. Heck most of the time they'll choose the venerable GNU autotools over Nmake and learning to use autotools is about as much fun as going to the dentist.

> Has this perhaps been discussed in the past ?

Yes, extensively. And while there are a couple of individuals who expressed sadness that the non-ksh code now has second class status they weren't willing to commit to maintain that code. The argument for keeping that code visible boiled down to "someone, some day, might want to use that code." That's why we created two branches to make it as easy as `git checkout 2016-01-10-beta` to gain access to it.

To the extent the current *README.md* document is not adequately clear about all of these we welcome suggestions for improving it.
