### ISSUE TITLE
Setup Coverity Scan for this project

### ISSUE THREAD

**Issue by krader1961** [att/ast#327]
The [Coverity Scan](https://scan.coverity.com/) static analysis service is invaluable for identifying problems with code. We should enroll this project with that service.

**Comment by siteshwar** [comment]
We have been using coverity within Red Hat to scan ksh package builds. I agree that we should use it to scan upstream code too.

**Comment by catull** [comment]
How frequent do you want to run it ?
Is it a manual task, automated ?

If automated, is it run monthly, weekly ?
If it scans on each merge/commit, it would create an entire report that is likely not read.

I support the scanning, it is miles better than relying on clang / gcc to issue warnings.

**Comment by siteshwar** [comment]
Our `.travis.yml` file already started to look strange, so I am going to avoid mixing up configurations for coverity builds into it. Since there are API limits in coverity and it is recommened by coverity documentation to use separate branch to trigger builds, I am going to write a separate `.travis.yml` file for it. This file can be copied to `.travis.yml` file each time we want to trigger coverity scan.

**Comment by siteshwar** [comment]
For the record, coverity builds do not work with macOS due to this error:

```
[ERROR] System Integrity Protection is enabled. In order to use cov-build,
this must be disabled. If you are confident that SIP has been
disabled, pass --no-sip-check to bypass this check.
```
