### ISSUE TITLE
What to do about builtins `mkservice` and `eloop`?

### ISSUE THREAD

**Issue by krader1961** [att/ast#348]
Builtins `mkservice` and `eloop` are commented out of *src/cmd/ksh93/include/builtins.h* and *src/cmd/ksh93/data/builtins.c* (i.e., hidden behind `#if 0`). There is no mention of them in the existing change log files. What do we want to do with these commands? Should they be enabled or removed?

**Comment by dannyweldon** [comment]
Has anyone subscribed to this repo tested these to see if they are working?

I think it would be useful to be able to run services in `ksh`.

**Comment by catull** [comment]
I have selected to "Watch" this repo.

The notifications I receive are for commits and issue activities, such as a new issue opened, an issue closing or comments added to issues.

Works for me.

**Comment by krader1961** [comment]
> Works for me.

Huh? The `mkservice` and `epoll` commands are hidden inside `#if 0...#endif` blocks. They effectively don't exist:

```
$ mkservice
ksh: mkservice: not found [No such file or directory]
```

> Has anyone subscribed to this repo tested these to see if they are working?

Seems unlikely other than a member of the AT&T that worked on the project. The embedded documentation is below. The ID string implies this was implemented in 2001 but there is no mention of it in any of the RELEASE files.

```
[-?\n@(#)$Id: mkservice (AT&T Research) 2001-06-13 $\n]" USAGE_LICENSE
[+NAME? mkservice - create a shell server ]
[+DESCRIPTION?\bmkservice\b creates a tcp or udp server that is
implemented by shell functions.]
[+?The \aservice_path\a must be of the form \b/dev/tcp/localhost/\b\aportno\a
or \b/dev/udp/localhost/\b\aportno\a depending on whether the
\btcp\b or \budp\b protocol is used.  \aportno\a is the port
number that the service will use.]
[+?The shell variable \avarname\a is associated with the service.  This
variable can have subvariables that keeps the state of all
active connections.  The functions \avarname\a\b.accept\b,
\avarname\a\b.action\b and \avarname\a\b.close\b implement the
service as follows:]{
[+accept?This function is invoked when a client tries to connect
to the service.  It is called with an argument which
is the file descriptor number associated with the
accepted connection.  If the function returns a non-zero
value, this connection will be closed.]
[+action?This function is invoked when there is data waiting
to be read from one of the active connections.  It is
called with the file descriptor number that has data
to be read.  If the function returns a non-zero
value, this connection will be closed.]
[+close?This function is invoked when the connection is closed.]
}
[+?If \avarname\a is unset, then all active connection, and the service
itself will be closed.]
```

I've written one trivial network service in bash because I didn't want to add a dependency on another language. It was really hard to implement make it robust. I would definitely not do it a again. I would use C, Go, Python, or anything other than a shell script. Whether the experimental `mkservice` ksh command makes using ksh for such things a good idea is debatable.

**Comment by siteshwar** [comment]
It was not shipped with the last stable release. And with the kind of service they provide, I don't think we should ship them in the next release either.

**Comment by dannyweldon** [comment]
These builtins would be useful to be used at some point as the basis for creating a debugging builtin that supports `DBGP`.  That way `ksh` scripts could easily be interactively debugged using virtually any modern editor/ide.

**Comment by krader1961** [comment]
@dannyweldon I don't see why the `mkservice` and `eloop` capabilities need to be exposed as builtin commands in order to provide the sort of debugging capability you describe. Unless, obviously, you're envisioning that capability being implemented as a ksh script. But it seems to me these commands were implemented because the author felt that ksh could serve as a general purpose language on a par with Python. Which isn't realistic without breaking from POSIX 1003.

**Comment by dannyweldon** [comment]
@krader1961.  Yes, my first thoughts on how to implement this would be to first write it as a `ksh` function that gets called as part of the `DEBUG` trap as a POC and then convert that to C.  And having the `mkservice` builtin would make that much easier than using pure shell code as you said before.  I assumed that I would then be able to easily use the `mkservice` builtin from within the C code for the same purpose, but I'm not sure how easy that would be, and if you think it can be done easily in C if needed, then so be it.  But I suppose code could be borrowed from the mkservice builtin without having to expose it as a builtin.

Apologies as I have not yet submitted my ideas for extending the language, as I have been very busy with other things, but I will try to get that done soon for people to comment on, and I understand that code reliability is the highest priority.

**Comment by KeithBierman** [comment]
>
> But it seems to me these commands were implemented because the author felt
> that ksh could serve as a general purpose language on a par with Python.
> Which isn't realistic without breaking from POSIX 1003.


David Korn appears to have felt otherwise.

https://news.slashdot.org/story/01/02/06/2030205/david-korn-tells-all

w.r.t. to this discussion in general, I think these two quotes shed some
light on DK's thinking

".... The primary focus of ksh93 is scripting and in this arena it
certainly outshines bash. ksh93 runs builtin shell commands much faster
than bash.

There is actually a third area of shell functionality which is related to
extensibility. In this area ksh93 should be compared to tcl. ksh93 is
implemented as a reusable library with a C language API for adding builtins
and accessing shell internals. It can be embedded in other programs. For
example, dtksh, which is part of the Common Desktop Environment (CDE), uses
ksh93 as a library. Similarly, tksh, (written by Jeff Korn) which uses the
tk library for graphics, uses ksh93 as a library.​"​

"
It is hard to argue that ksh is any better for interaction, given all the
features in tcsh and zsh. But the scripting features in ksh93 are far more
advanced than any other shell that I am aware of. For scripting, I feel
that ksh is more in the category of perl/tcl/python and I would like to see
debates/comparisons for those languages rather than the antiquated
bash/csh/etc.
​"​

​I'm not going to argue either way; it just seemed to me that David did
provide some insight into goals and motivation in this interview.​




Keith Bierman
khbkhb@gmail.com
