### ISSUE TITLE
Missing `alarm` man page

### ISSUE THREAD

**Issue by marcastel** [att/ast#35]
Unable to locate any documentation on the `alarm` builtin.
According to this [thread](https://www.mail-archive.com/ksh93-integration-discuss@mail.opensolaris.org/msg02974.html), circa 2006, David Korn was not _ready to publicise_ -- he had concerns about possible conflicts with _new_ functionality. What's the status today?

In summary:
a) Is the alarm builtin usable?
b) Can we trace sufficient usage information to build a man page?

Cheers, don

**Comment by dannyweldon** [comment]
It does work.  As he said that he might consider adding a self-generating man page anyway, it can't hurt to do one, just add a note about David's warning.

Finbarr's blog has some examples of usage:
http://blog.fpmurphy.com/2008/12/mysterious-ksh93-alarm-builtin.html

Don, would you be willing to have a go and submit a pull request?  :)

The variable to update is sh_optalarm in src/cmd/ksh93/data/builtins.c

**Comment by marcastel** [comment]
Thanks for the feedback Danny. I will try it out.

No problems for the pull request. They may be some lag time here as I have troubles compiling the code these days on my mac box. But will sure do so :-)

**Comment by krader1961** [comment]
When I opened issue #646 I didn't realize this issue existed. Normally I would close the newer issue but I'm going to close this one instead since I don't think we want to document this feature. As explained in the newer issue if a feature is undocumented after existing for more than ten years I don't think we want to bother with it. There are so many problems that need to be fixed, many introduced in the ksh93v- beta release, I don't think we can justify expending effort on the undocumented `alarm` builtin.
