### ISSUE TITLE
Syntax error while running pty.sh test

### ISSUE THREAD

**Issue by catull** [att/ast#358]
The tests run on Fedora produced little diagnostic output until recently.

I ran all tests with `meson test -v`, the workspace is unmodified from commit 19d0620a72fe8c1b0ae43ae198f1f505fc9320c1.

This log statement appears:

```log
....
ast.git/src/cmd/ksh93/tests/pty.sh: line 32: syntax error at line 41: `(' unmatched
....
```

I am preparing a PR for it.

**Comment by catull** [comment]
Come to think of it, the test `pty.sh` is rather pointless right now.

On both macOS and Fedora, the test ends on line 37, because neither platform has a command `pty`, thus the `pty` is not tested at all.

There is a command in src/cmd/builtin/pty.c.

However, after building an installing the `ksh`, after starting it in a separate terminal, `pty` is not known:

```sh
# echo $KSH_VERSION
Version BIJ 93v- 2014-12-24
# pty -h
ksh: pty: not found [No such file or directory]
```

**Comment by krader1961** [comment]
> However, after building an installing the ksh, after starting it in a separate terminal, pty is not known:

Correct. It is not currently built because it is part of the external commands in directory *src/cmd/builtin/*. None of which are currently built because we're still discussing whether this project should include those commands. Probably the only command in that directory which should be built is the `pty` command. Even there I think it is debatable whether it should be an external command or a ksh builtin.
