### ISSUE TITLE
Shall we deprecate shcomp ?

### ISSUE THREAD

**Issue by siteshwar** [att/ast#365]
`shcomp` is used to compile shell scripts into a binary format that can be executed by ksh. I would like to know if anyone subscribed to this repository is using it. I have never seen any bug reports about it. Searching for ast-developers mailing list only shows bug reports about failing test cases. If you are using it and would like to see it shipped in future releases, please comment on this thread.

**Comment by krader1961** [comment]
Personally, I don't see the point of the added complexity since a ksh script should never be CPU bound. If it is then it's probably the wrong tool for the job. Somewhat surprisingly the sole module that deals with this, *src/cmd/ksh93/sh/shcomp.c*, is very short at only 165 lines -- most of which is setup.

The *lib/package/ast-open.README* document lists numerous bugs related to this facility. I also find it odd that we have to compile ksh a second time to get a `shcomp` command. I would have set things up so that the ksh binary behaves as `shcomp` if it was invoked by that name else it behaves as `ksh`. Possibly with an optional flag to force compilation mode; e.g., `ksh --shcomp script_file binary_file`.

Having said all that a quick look at the relevant code suggests this feature is the least of our problems in terms of complexity or dead wood to be pruned. But if no one is using it we should drop it. FWIW, I had never heard of this ksh feature before I started contributing a few months ago.

P.S., Consider this output from `man shcomp` on Ubuntu:

```
ORIGIN OF THIS MAN PAGE
       This  man  page  was  written  by  Christophe Martin <Schplurtz@free.fr> for the
       Debian GNU/Linux system. It is based on "shcomp --man" output.
```

It shouldn't be necessary for distros to rewrite/repackage the documentation embedded in the source code. That huge blobs of man page text is embedded as C data structures is an anti-pattern as far as I'm concerned. That text should be in separate files. Running `some_command --man` can still display the man page without it being embedded in the source code. See how Fish shell does it for a better example of how to solve this problem.

**Comment by kdudka** [comment]
I see that numerous shcomp-related bug fixes landed after ksh93:
```
    98-04-30  A bug in shcomp relating to compound variables was fixed.
    99-03-31  A bug in shcomp for compilation of unary operators with [[...]]
              has been fixed.
    01-04-30  The shcomp command was modified so that it can work in an
              EBCIDIC environment and that binary scripts are portable
              across environments.
    01-04-30  A self generating man page has been added to shcomp.  Also,
              shcomp now stops compiling when it finds an exit or exec
              command and copies the remainder so that it can be used
              for standard input.
    04-08-01  The shcomp command has been modified to process alias commands
              under some conditions.
    08-11-20  A bug which could cause a core dump if a function compiled with
              shcomp was found has been fixed.
    09-12-09  A bug where shcomp dumped core on certain syntax errors has been fixed.
    10-04-15  A bug which caused scripts containing user defined math functions to
              fail to compile with shcomp has been fixed.
    10-08-04  A bug which caused an exception when processing scripts compiled
              with shcomp -n has been fixed.
    10-11-18  A bug in which shcomp -n was not processing double quotes correctly
              has been fixed.
    12-06-08  A bug in which running shcomp on a program containg namespace
              could core dump has been fixed.
    13-05-06  A bug in which shcomp failed to compile some scrips that defined
              enums has been fixed.
```
... which suggests it is not completely unused.  It has also been covered by the upstream test-suite until ea9dc1b307fcf8365f322bf25e99bb09aaa8d639.  Needless to say that a similar feature exists (and works properly) in zsh:

http://zsh.sourceforge.net/Doc/Release/Shell-Builtin-Commands.html#index-zcompile

**Comment by dannyweldon** [comment]
Also `ubuntu` (so assuming `debian` also) ships `shcomp` with the `ksh` package.  The magic bytecode string for compiled scripts has been added to the `file` command as of 5.29.

FWIW, I have also done some experiments using `shcomp` to compile a `ksh` script to bytecode, then convert that to a c header file and use a short c stub to execute that using `libshell`.  That allows one to easily convert a script to a compiled standalone binary, combined with `ksh`'s builtins of the standard commands, gives you a very portable standalone executable.

**Comment by siteshwar** [comment]
@kdudka We have disabled only a few tests for `shcomp`. Almost all of the tests are still enabled and passing for `shcomp`. You can verify it by running `meson test`.

**Comment by kdudka** [comment]
Thank you for clarifying it!  Then it looks to me like a consistently maintained feature, which has pretty good test coverage, and not something we should deprecate now and remove a while later.

**Comment by KeithBierman** [comment]
While I've never used it, the typical use case I've seen others use it for
is  "security". That is, applications suites which used ksh scripts to
"wrap" their core binaries who did NOT wish the user to be able to tweak
the scripts ...


Keith Bierman
khbkhb@gmail.com
303 997 2749

**Comment by krader1961** [comment]
@KeithBierman, That's an interesting observation. That use case is much more compelling than compiling scripts simply to avoid the cost of parsing them each time they're run.

Closing since the consensus is the feature does have at lest one legitimate use case and is probably stable enough that it's not going to be an ongoing source of problems.
