### ISSUE TITLE
Compilation failure: undeclared identifier 'CLOCK_REALTIME'

### ISSUE THREAD

**Issue by McDutchie** [att/ast#404]
Compiling the current trunk version (as of 01d17e945381fb0c6aef4ef13e041477c1ea2f15) on Mac OS X 10.11.6 (clang 8.0.0) fails with the following errors.

````
[347/533] Compiling C object 'src/lib/libast/ast@sta/tm_tvgettime.c.o'.
FAILED: src/lib/libast/ast@sta/tm_tvgettime.c.o 
ccache cc  -Isrc/lib/libast/ast@sta -Isrc/lib/libast -I../src/lib/libast -I. -I../ -Isrc/lib/libast/tm -I../src/lib/libast/tm -Isrc/lib/libast/vmalloc -I../src/lib/libast/vmalloc -Isrc/lib/libast/misc -I../src/lib/libast/misc -Isrc/lib/libast/string -I../src/lib/libast/string -Isrc/lib/libast/port -I../src/lib/libast/port -Isrc/lib/libast/path -I../src/lib/libast/path -Isrc/lib/libast/sfio -I../src/lib/libast/sfio -Isrc/lib/libast/comp -I../src/lib/libast/comp -Isrc/lib/libast/cdt -I../src/lib/libast/cdt -Isrc/lib/libast/aso -I../src/lib/libast/aso -I../src/lib/libast/features -I../src/lib/libast/include -Xclang -fcolor-diagnostics -pipe -Wall -Winvalid-pch -O0 -g -std=gnu99 -D_GNU_SOURCE -Werror=implicit -Os '-DUSAGE_LICENSE=""' -D_BLD_ast -DGCC_4_1PLUS_64_BIT_MEMORY_ATOMIC_OPERATIONS_MODEL=1 -MMD -MQ 'src/lib/libast/ast@sta/tm_tvgettime.c.o' -MF 'src/lib/libast/ast@sta/tm_tvgettime.c.o.d' -o 'src/lib/libast/ast@sta/tm_tvgettime.c.o' -c ../src/lib/libast/tm/tvgettime.c
../src/lib/libast/tm/tvgettime.c:30:5: error: implicit declaration of function 'clock_gettime' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    clock_gettime(CLOCK_REALTIME, &s);
    ^
../src/lib/libast/tm/tvgettime.c:30:19: error: use of undeclared identifier 'CLOCK_REALTIME'
    clock_gettime(CLOCK_REALTIME, &s);
                  ^
2 errors generated.
[348/533] Compiling C object 'src/lib/libast/ast@sta/tm_tvsettime.c.o'.
FAILED: src/lib/libast/ast@sta/tm_tvsettime.c.o 
ccache cc  -Isrc/lib/libast/ast@sta -Isrc/lib/libast -I../src/lib/libast -I. -I../ -Isrc/lib/libast/tm -I../src/lib/libast/tm -Isrc/lib/libast/vmalloc -I../src/lib/libast/vmalloc -Isrc/lib/libast/misc -I../src/lib/libast/misc -Isrc/lib/libast/string -I../src/lib/libast/string -Isrc/lib/libast/port -I../src/lib/libast/port -Isrc/lib/libast/path -I../src/lib/libast/path -Isrc/lib/libast/sfio -I../src/lib/libast/sfio -Isrc/lib/libast/comp -I../src/lib/libast/comp -Isrc/lib/libast/cdt -I../src/lib/libast/cdt -Isrc/lib/libast/aso -I../src/lib/libast/aso -I../src/lib/libast/features -I../src/lib/libast/include -Xclang -fcolor-diagnostics -pipe -Wall -Winvalid-pch -O0 -g -std=gnu99 -D_GNU_SOURCE -Werror=implicit -Os '-DUSAGE_LICENSE=""' -D_BLD_ast -DGCC_4_1PLUS_64_BIT_MEMORY_ATOMIC_OPERATIONS_MODEL=1 -MMD -MQ 'src/lib/libast/ast@sta/tm_tvsettime.c.o' -MF 'src/lib/libast/ast@sta/tm_tvsettime.c.o.d' -o 'src/lib/libast/ast@sta/tm_tvsettime.c.o' -c ../src/lib/libast/tm/tvsettime.c
../src/lib/libast/tm/tvsettime.c:33:12: error: implicit declaration of function 'clock_settime' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    return clock_settime(CLOCK_REALTIME, &s);
           ^
../src/lib/libast/tm/tvsettime.c:33:26: error: use of undeclared identifier 'CLOCK_REALTIME'
    return clock_settime(CLOCK_REALTIME, &s);
                         ^
2 errors generated.
````

**Comment by krader1961** [comment]
@McDutchie, Thanks for reporting this. I've been building this on macOS 10.12 and 10.13 from the first day I started contributing since it is my primary desktop OS. I don't see that failure. And it seems unlikely to me that macOS 10.11 doesn't have that symbol in the *time.h* header.

What commands did you run? I ask because on my system I see `cc`, not `ccache cc`. Which implies that when you ran the initial `meson` config you had one or more unusual env vars. You definitely do not want, or need, to use [`ccache`](https://en.wikipedia.org/wiki/Ccache) when building this project using Meson. If you're trying to cross compile the project that won't work due to how platform feature detection works.

**Comment by McDutchie** [comment]
In fact, Mac OS X 10.11 does *not* have that symbol in the time.h header.

    grep -r CLOCK_REALTIME /usr/include

comes up empty.

I have no unusual env vars, nothing that contains 'ccache'. I do have ccache installed. Could meson be detecting it automatically?

Uninstalling ccache and recompiling yields identical results (minus the 'ccache' in the output):

````
[346/533] Compiling C object 'src/lib/libast/ast@sta/tm_tvsettime.c.o'.
FAILED: src/lib/libast/ast@sta/tm_tvsettime.c.o 
cc  -Isrc/lib/libast/ast@sta -Isrc/lib/libast -I../src/lib/libast -I. -I../ -Isrc/lib/libast/tm -I../src/lib/libast/tm -Isrc/lib/libast/vmalloc -I../src/lib/libast/vmalloc -Isrc/lib/libast/misc -I../src/lib/libast/misc -Isrc/lib/libast/string -I../src/lib/libast/string -Isrc/lib/libast/port -I../src/lib/libast/port -Isrc/lib/libast/path -I../src/lib/libast/path -Isrc/lib/libast/sfio -I../src/lib/libast/sfio -Isrc/lib/libast/comp -I../src/lib/libast/comp -Isrc/lib/libast/cdt -I../src/lib/libast/cdt -Isrc/lib/libast/aso -I../src/lib/libast/aso -I../src/lib/libast/features -I../src/lib/libast/include -Xclang -fcolor-diagnostics -pipe -Wall -Winvalid-pch -O0 -g -std=gnu99 -D_GNU_SOURCE -Werror=implicit '-DUSAGE_LICENSE=""' -D_BLD_ast -DGCC_4_1PLUS_64_BIT_MEMORY_ATOMIC_OPERATIONS_MODEL=1 -MMD -MQ 'src/lib/libast/ast@sta/tm_tvsettime.c.o' -MF 'src/lib/libast/ast@sta/tm_tvsettime.c.o.d' -o 'src/lib/libast/ast@sta/tm_tvsettime.c.o' -c ../src/lib/libast/tm/tvsettime.c
../src/lib/libast/tm/tvsettime.c:33:12: error: implicit declaration of function 'clock_settime' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    return clock_settime(CLOCK_REALTIME, &s);
           ^
../src/lib/libast/tm/tvsettime.c:33:26: error: use of undeclared identifier 'CLOCK_REALTIME'
    return clock_settime(CLOCK_REALTIME, &s);
                         ^
2 errors generated.
````

````
[349/533] Compiling C object 'src/lib/libast/ast@sta/tm_tvgettime.c.o'.
FAILED: src/lib/libast/ast@sta/tm_tvgettime.c.o 
cc  -Isrc/lib/libast/ast@sta -Isrc/lib/libast -I../src/lib/libast -I. -I../ -Isrc/lib/libast/tm -I../src/lib/libast/tm -Isrc/lib/libast/vmalloc -I../src/lib/libast/vmalloc -Isrc/lib/libast/misc -I../src/lib/libast/misc -Isrc/lib/libast/string -I../src/lib/libast/string -Isrc/lib/libast/port -I../src/lib/libast/port -Isrc/lib/libast/path -I../src/lib/libast/path -Isrc/lib/libast/sfio -I../src/lib/libast/sfio -Isrc/lib/libast/comp -I../src/lib/libast/comp -Isrc/lib/libast/cdt -I../src/lib/libast/cdt -Isrc/lib/libast/aso -I../src/lib/libast/aso -I../src/lib/libast/features -I../src/lib/libast/include -Xclang -fcolor-diagnostics -pipe -Wall -Winvalid-pch -O0 -g -std=gnu99 -D_GNU_SOURCE -Werror=implicit '-DUSAGE_LICENSE=""' -D_BLD_ast -DGCC_4_1PLUS_64_BIT_MEMORY_ATOMIC_OPERATIONS_MODEL=1 -MMD -MQ 'src/lib/libast/ast@sta/tm_tvgettime.c.o' -MF 'src/lib/libast/ast@sta/tm_tvgettime.c.o.d' -o 'src/lib/libast/ast@sta/tm_tvgettime.c.o' -c ../src/lib/libast/tm/tvgettime.c
../src/lib/libast/tm/tvgettime.c:30:5: error: implicit declaration of function 'clock_gettime' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    clock_gettime(CLOCK_REALTIME, &s);
    ^
../src/lib/libast/tm/tvgettime.c:30:19: error: use of undeclared identifier 'CLOCK_REALTIME'
    clock_gettime(CLOCK_REALTIME, &s);
                  ^
2 errors generated.
````

**Comment by kdudka** [comment]
On Monday, February 12, 2018 3:57:16 AM CET Kurtis Rader wrote:
> You definitely do not want, or need, to
> use [`ccache`](https://en.wikipedia.org/wiki/Ccache) when building this
> project using Meson.

Why?  If I touch src/cmd/ksh93/include/defs.h, the rebuild is 10 times faster 
with ccache than without it (and it is even more noticeable on a machine with 
fewer CPU cores).


With ccache:

% touch ../src/cmd/ksh93/include/defs.h && time ninja
[...]
[127/127] Linking target src/cmd/ksh93/shcomp.
ninja: real 0.307, user 0.416, sys 0.304, cpu 234%


Without ccache:

% touch ../src/cmd/ksh93/include/defs.h && time ninja
[...]
[127/127] Linking target src/cmd/ksh93/shcomp.
ninja: real 3.090, user 17.419, sys 2.892, cpu 657%

**Comment by krader1961** [comment]
@McDutchie, Okay, it looks like the old AST code has a feature test for the availability of `CLOCK_REALTIME` which didn't get translated to the Meson config. I'll take care of that. I wouldn't be surprised to learn that macOS 10.6 didn't implement that mechanism but I do find it slightly surprising 10.11 doesn't. Oh well.

> Could meson be detecting it automatically?

Yes, I looked at the Meson source and its *mesonbuild/environment.py* module has explicit support for detecting if ccache is installed.

Note that 'grep -r CLOCK_REALTIME /usr/include` may not provide reliable results on macOS since the root of the headers actually used may be elsewhere. On my macOS 10.13 system there is no */usr/include*. Compiling a dummy program that does nothing but include a standard system header and compiling with `clang -h` shows they're rooted at *
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/*.

@kdudka, Okay. Presumably ccache is ignoring the timestamps and calculating a SHA, or other, message digest to decide of all the source files involved in a given compilation unit to decide if an actual recompilation is needed. Which is extremely useful in a corporate environment like Google or Red Hat where it is likely that different developers are compiling the same version of a module but which might have different timestamps on their workstations (or cluster/cloud based distributed build nodes). It's certainly not something you need to setup just to get faster local builds. It didn't occur to me that @McDutchie might be working in such an environment.

**Comment by krader1961** [comment]
Note that the original Nmake based feature test has one bogosity and one questionable test. The bogosity is testing whether it supports a `struct struct timezone*` argument or simply requires a NULL pointer for that argument. Which, given that the code doesn't pass anything other than `NULL` for either case is silly. It also tests for a `gettimeofday()` function that only takes one argument. I'm going to skip that feature test because there is no reason to think any system this will ever be built on has such a non-standard implementation.

**Comment by kdudka** [comment]
On Tuesday, February 13, 2018 12:08:17 AM CET Kurtis Rader wrote:
> @kdudka, Okay. Presumably ccache is ignoring the timestamps and calculating
> a SHA, or other, message digest to decide of all the source files involved
> in a given compilation unit to decide if an actual recompilation is needed.

timestamps are irrelevant for ccache because ccache is not a build system but 
a compiler wrapper which calls C/C++ preprocessor and hashes its result (to 
avoid running compiler on the same input repeatedly).  I used timestamp update 
in my minimal example just to show you that the speedup is significant.  But 
you can as well change the actual content of a header file without needing
to recompile some (or even all) the C/C++ units that directly or indirectly 
include it.

> Which is extremely useful in a corporate environment like Google or Red Hat
> where it is likely that different developers are compiling the same version
> of a module but which might have different timestamps on their workstations
> (or cluster/cloud based distributed build nodes). It's certainly not
> something you need to setup just to get faster local builds. It didn't
> occur to me that @McDutchie might be working in such an environment.

Nope.  ccache is mainly useful when you develop/debug something locally to 
shorten the edit-compile-run cycle.  While we have a ccache plug-in in mock 
(the tool that builds RPM packages in a reproducible way), the plug-in is
not used for our production builds.

**Comment by McDutchie** [comment]
Yes, ccache may not be useful for one-time local builds, but is certainly useful if you're debugging or developing things. Debugging local builds can get repetitive as you wipe builds and start over. My local ccache has a hit rate of just over 50% so it's certainly doing a bit of good.

Meanwhile, after applying the diff from krader1961's commit cited above, tvgettime.c compiles, but tvsettime.c still fails, with the same error messages as cited above.

**Comment by krader1961** [comment]
> Nope.  ccache is mainly useful when you develop/debug something locally to shorten the edit-compile-run cycle.

AFAICT that's only true for broken build systems like the legacy AST Nmake tool chain. Which in my experience fails to correctly detect changes to files that affect the build. Using ccache should not make one bit of difference for local builds of `ksh` unless you're altering the modified timestamp of a file without changing its content. And if you're changing the timestamp without altering the contents I have to ask "why?" I'm not seeing any need to use ccache to do a local build of `ksh` now that we're using Meson. But then I rarely perform actions that change the modification timestamp of local files which don't change the content.

In any case using `ccache`, now that I understand what it does, should not be a source of problems.

@McDutchie, Feel free to reopen this, or open a new issue, if the change I committed still does not allow you to build a working `ksh` binary.

**Comment by McDutchie** [comment]
I can confirm that your commit fixed the problem for me. Thanks.

**Comment by kdudka** [comment]
On Wednesday, February 14, 2018 7:18:53 AM CET Kurtis Rader wrote:
> AFAICT that's only true for broken build systems like the legacy AST Nmake
> tool chain. Which in my experience fails to correctly detect changes to
> files that affect the build. Using ccache should not make one bit of
> difference for local builds of `ksh` unless you're altering the modified
> timestamp of a file without changing its content. And if you're changing
> the timestamp without altering the contents I have to ask "why?" I'm not
> seeing any need to use ccache to do a local build of `ksh` now that we're
> using Meson. But then I rarely perform actions that change the modification
> timestamp of local files which don't change the content.

Kurtis, I do not know why you keep repeating the misinformation over and over.  Changing a timestamp was just a minimal example to show you the speedup, not the most common workflow where you can take advantage of ccache.

It is important to understand that you can change the _content_ of a header file in a way that it does not result in changing the preprocessed code of some (or even all) the C/C++ units that directly or indirectly include it.

You can try the following example instead:
```
% ccache -zCs
Statistics cleared
Cleared cache
cache directory                     /home/kdudka/.ccache
primary config                      /home/kdudka/.ccache/ccache.conf
secondary config      (readonly)    /etc/ccache.conf
cache hit (direct)                     0
cache hit (preprocessed)               0
cache miss                             0
cache hit rate                      0.00 %
cleanups performed                    16
files in cache                         0
cache size                           0.0 kB
max cache size                       5.0 GB

% ninja
% ccache -s
cache directory                     /home/kdudka/.ccache
primary config                      /home/kdudka/.ccache/ccache.conf
secondary config      (readonly)    /etc/ccache.conf
cache hit (direct)                     0
cache hit (preprocessed)               0
cache miss                           125
cache hit rate                      0.00 %
called for link                        2
cleanups performed                    16
files in cache                       498
cache size                          12.1 MB
max cache size                       5.0 GB

% sed -e 's/maxumum/maximum/' -e 's/defintion/definition/' \
      -i ../src/cmd/ksh93/include/defs.h
% ninja
% ccache -s                                                                                  
cache directory                     /home/kdudka/.ccache
primary config                      /home/kdudka/.ccache/ccache.conf
secondary config      (readonly)    /etc/ccache.conf
cache hit (direct)                     0
cache hit (preprocessed)             125
cache miss                           125
cache hit rate                     50.00 %
called for link                        4
cleanups performed                    16
files in cache                       623
cache size                          12.7 MB
max cache size                       5.0 GB
```

You can see that it was not only timestamp what changed, still I had 100% hit ratio on the subsequent rebuild (50% hit ratio including the initial build).

Anyway, thank you for fixing the build issue, which was unrelated to ccache!
