### ISSUE TITLE
print -s output lost when using -f

### ISSUE THREAD

**Issue by qbarnes** [att/ast#425]
This works as expected with print -s sending the output to the history file:
```
$ print -s "cd -- '$PWD'"
$ history -2
7518    print -s "cd -- '$PWD'"
7519    cd -- '/home/qbarnes'
7520    history -2
```

This works as expected displaying the output to standard out:
```
$ print -f 'cd -- %q\n' "$PWD"   
cd -- /home/qbarnes/github/att/ast
```

However, when the command immediately above is used with -s, the output goes nowhere:
```
$ print -s -f 'cd -- %q\n' "$PWD"
$ history -2
7513    print -f 'cd -- %q\n' "$PWD"
7514    print -s -f 'cd -- %q\n' "$PWD"
7515    history -2
```

I reproduced this problem with the current master branch (77b75138) using x86_64 host running Linux RHEL 7.4 and on my MacOS El Capitan running ksh AJM 93u+ 2012-08-01.  The problem happened also with the oldest Linux ksh binary I still have around (release 2007-11-05).

This seems like an obvious bug to me, but I'm open to the idea that I'm missing something in the documentation where -s and -f are somehow incompatible.  Bug or feature?

**Comment by perette** [comment]
Octal dumping the .sh_history file shows the commands are separated by \n\0 sequences (newline-null), or \n\0\0.  (It seems to use an even number of bytes for each entry.)  `print -s` implicitly inserts the newlines and gets the nulls right, so it works.

`print -s -f` puts in whatever sequence you tell it, but then inserts some cruft where the null should be.  Explicitly including the null in the format string makes it work right:
```
$ print -s -f 'cd -- %q\n\0' "$PWD"
$ history -2
1157	print -s -f 'cd -- %q\n\0' "$PWD"
1158	cd -- /home/perette
1159	history -2
```
Although the number of nulls being written does vary from the usual behavior, it seems to work fine.

Perhaps something is running off the end of a buffer, expecting the null to be there, instead encountering whatever cruft is in memory there?

**Comment by perette** [comment]
```
$ print -s -f 'cd -- %q\n' "$PWD"
$ history -2
730	print -s -f 'cd -- %q\n' "$PWD"
731	cd -- /home/perette/Projects/ast/build/src/cmd/ksh93
732	history -2
```

Patch is attached.

[ksh-printf-s-f.patch.txt](https://github.com/att/ast/files/1827795/ksh-printf-s-f.patch.txt)

**Comment by siteshwar** [comment]
@perette Thanks for the patch, however I could not understand how skipping `sfsync()` on history file fixes this issue. If you open `~/.sh_history` file after the command, it seems to be updated correctly. It looks like `history` command misbehaves if command does not end with a newline character. I suspect the bug lies somewhere else.

**Comment by perette** [comment]
The sfsync() where I added the condfitional syncs without setting `hp->histflush = 1`, as is done in hist_flush (history.c:668) which is called inside the `if (sflag)` at print.c:373.  When `histflush` is 0, the behavior of hist_write to flush the stream without imposing the required formatting (i.e., adding the newlines/nulls (see history.c:705).)

Not flushing at print.c:353 means it's still unflushed when it hits the`if (sflag)` condiion at :373, so hist_flush is called, where hp->histflush is set to 1, which calls sfwrite() to flush, which invokes hist_write as a callback, which then does the Right Thing since hist_flush is non-0.  Well, right thing insofar as it goes into the code that's adjusts the file formatting that adds the null and newlines, instead of just flushing the raw buffer.  However, there's the buffer overflow edge case that I started a separate issue about.

It does fix this issue though, as evidenced by testing.  Still, please do review; I am new to this code, and I could have missed side-effects.
