### ISSUE TITLE
'command -p' broken in certain contexts

### ISSUE THREAD

**Issue by McDutchie** [att/ast#426]
`command -p` is supposed to run a command with the default system `PATH` as opposed to the current `PATH`, so it is guaranteed to get a POSIX standard utility. But:

`$ ksh -c 'command -p ls'`
`ksh: ls: not found`
`$ ksh -c '(command -p ls)'`
`ksh: ls: not found`
`$ ksh -c 'echo $(command -p ls)'`
(file listing is output)
`$ ksh -c 'command -p ls & wait'`
(file listing is output)

Bug confirmed on:
* Version JM 93t+ 2010-03-05
* Version AJM 93u+ 2012-08-01
* current git

Bug *not* present on:
* Version M 1993-12-28 r

(previously reported [on the ast-developers list](http://narkive.com/rqDYjbtM.1))

**Comment by krader1961** [comment]
Any idea what this vague sentence in the documentation means?

> The -p option causes a default path to be searched rather than the one defined by the value of PATH.

What is the "default path"? Using the `-p` flag causes option `SH_DEFPATH` to be turned on. Which in turn appears to cause `shp->defpathlist` to be used instead of `shp->pathlist`.  It looks like this involves iterating over `$PATH` and passing each element to `path_chkpaths()` to decide if it is allowed in the "default path".

Instrumenting `b_command()` shows that in an interactive shell (at least on my macOS system) `shp->defpathlist` is a NULL pointer and `shp->pathlist` is a linked list that mirrors my `$PATH`. When running a non-interactive shell both members are NULL pointers whether or not the `-p` flag is used. But without that flag it seems to fallback to the value of `$PATH` deeper in the code.

Also, note that it works in an interactive shell or if you force interactive mode; e.g., `ksh -ic 'command -p ls'` works. So it seems likely this has something to do with the difference in how interactive versus non-interactive shells are initialized.

**Comment by McDutchie** [comment]
> Any idea what this vague sentence in the documentation means?
>> The -p option causes a default path to be searched rather than the one defined by the value of PATH.

[POSIX spec for the 'command' utility](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/command.html#tag_20_22): "**-p** –  Perform the command search using a default value for PATH that is guaranteed to find all of the standard utilities."

Effectively this means that, instead of `$PATH`, the path should be searched that is output by the command `getconf PATH` on the current system, or by the `confstr`(3) function (name `_CS_PATH`).

**Comment by siteshwar** [comment]
It is a case of use before initialization. If `ksh` is started as an interactive shell, default path variable is getting initialized when `/etc/ksh.kshrc` is sourced. This is how the stacktrace looks like :

```
#0  path_init (shp=0x7ba560 <sh>) at ../src/cmd/ksh93/sh/path.c:378
#1  0x0000000000493c9b in path_opentype (shp=0x7ba560 <sh>, name=0x563e38 <e_sysrc> "/etc/ksh.kshrc", pp=0x0, fun=0)
    at ../src/cmd/ksh93/sh/path.c:417
#2  0x0000000000493ed7 in path_open (shp=0x7ba560 <sh>, name=0x563e38 <e_sysrc> "/etc/ksh.kshrc", pp=0x0)
    at ../src/cmd/ksh93/sh/path.c:446
#3  0x000000000046cb4a in sh_source (shp=0x7ba560 <sh>, iop=0x0, file=0x563e38 <e_sysrc> "/etc/ksh.kshrc")
    at ../src/cmd/ksh93/sh/main.c:94
#4  0x000000000046d24a in sh_main (ac=3, av=0x7fffffffdee8, userinit=0x0) at ../src/cmd/ksh93/sh/main.c:215
#5  0x0000000000497c33 in main (argc=3, argv=0x7fffffffdee8) at ../src/cmd/ksh93/sh/pmain.c:42
```
This file is not sourced when ksh is started as non-interactive shell. So default path variable does not get initialized. I have proposed #448 to fix it.
