### ISSUE TITLE
The ksh `functions` unit test runs an external `zzz` command if found in `$PATH` rather than the function of the same name

### ISSUE THREAD

**Issue by kernigh** [att/ast#429]
A test puts my OpenBSD machine to sleep. If I press the power button to wake my machine, it sleeps again. The test acts as if it is running `/usr/sbin/zzz` in a loop. There are several instances of `zzz` in the tests, so a test might be failing and running `/usr/sbin/zzz` by mistake.

1. My machine runs OpenBSD/amd64 6.2. I had enabled the daemon `apmd -A`. The daemon allows me to run `zzz` to sleep.
2. My login shell is OpenBSD's pdksh in `/bin/ksh`.
Its KSH_VERSION is `@(#)PD KSH v5.2.14 99/07/13.2`.
3. I had installed OpenBSD's ksh93 package. It's at `/usr/local/bin/ksh93`.
Its KSH_VERSION is `Version AJM 93u+ 2012-08-01`.
4. I cloned git master at commit 77b7513.
5. I ran `meson build --prefix=$HOME/prefix` and `ninja -C build`.
6. I ran `ninja -C build install`, but then in ~/prefix/bin, I renamed ksh to ksh93. I also renamed the manual page. My path has ~/prefix/bin before /usr/local/bin, so `whence ksh93` says `/home/kernigh/prefix/bin/ksh93`, and `whence ksh` says `/bin/ksh`.
7. I cd to ast/build and run `meson test`. The shell where I type `meson test` is OpenBSD's pdksh. I have `SHELL=/bin/ksh` in the environment.
8. I wait for tests. The "basic" tests take more than 60 seconds each.
9. The computer goes to sleep.
10. If I wake the computer, it goes to sleep again.
11. I switch off the power to the computer.

**Comment by krader1961** [comment]
Please explain the rationale for your step #6. I've been using the Meson build system to build and test ksh since it was originally introduced. I've done so on multiple platforms including OpenBSD 6.2. I've never done anything remotely like you've described. Neither have I had any problems with my machine running OpenBSD (or any other distro) going to sleep when running the ksh tests.

Please note that the AST ksh master branch has several serious bugs. Including at least one use-after-free bug that affects most of the tests.

**Comment by kernigh** [comment]
In step 6, I installed this project's ksh and renamed it from ~/prefix/bin/ksh to ~/prefix/bin/ksh93, because it was before OpenBSD's /bin/ksh in my path, but I want `ksh` to be OpenBSD's ksh, not this project's ksh.

Your OpenBSD machine will not sleep if the command `zzz` doesn't sleep. This might happen if apmd isn't running (check with `rcctl check apmd`), or the user can't write to `/var/run/apmdev`, or OpenBSD doesn't know how to sleep your hardware.

I now believe that I have found the problem in tests/functions.sh:

```
diff --git a/src/cmd/ksh93/tests/functions.sh b/src/cmd/ksh93/tests/functions.sh
index c7c80a8d..e9fbec69 100755
--- a/src/cmd/ksh93/tests/functions.sh
+++ b/src/cmd/ksh93/tests/functions.sh
@@ -267,9 +267,10 @@ function foobar
 chmod +x $tmp/foobar
 FPATH=$tmp
 cd $tmp
-print 'function zzz { return 0;}' > zzz
+# zzf, not zzz, because /usr/sbin/zzz puts BSD to sleep
+print 'function zzf { return 0;}' > zzf
 PATH=$PATH:
-zzz  2> /dev/null || err_exit 'function not found in . when $PWD is in FPATH'
+zzf 2> /dev/null || err_exit 'function not found in . when $PWD is in FPATH'
 PATH=${PATH%:}
 cd ~-
 autoload foobar
```

Somehow ksh didn't find function zzz but did find `/usr/sbin/zzz`, so my machine went to sleep.

I have about 54 failing tests. I suspect a problem with `vfork()`, but I'm not yet certain.

**Comment by krader1961** [comment]
There is no need to put the directory of the projects ksh binary in `$PATH`. Running `meson test` will automatically use it to execute the tests.

> I have about 54 failing tests. I suspect a problem with vfork(), but I'm not yet certain.

I also see 54 failing tests. However, note that some of the failures are likely because of OpenBSD quirks that the unit tests don't handle. Not due to any bug in the ksh program.

For example, the three variants of the `wchar` test used to fail because the `en_US.ISO-8859-15` and `zh_CN.GB18030` are not installed by default.

So a few months ago I added a check to see if those locales are valid and if not skip the tests that depend on them.

As for the problem with the `functions` unit test your workaround is fine for your system but we wouldn't merge it. That's because the test needs to be modified to ensure it doesn't use an external command with the same name as the autoloaded function it creates -- no matter what the command name is. Alternatively, if it is supposed to load the `zzz` function even if a command of the same name is found in `$PATH` then that bug should be fixed. Also, testing just the exit status is not a good way to verify the function was run. That's because, as you found, if a command of the same name exists and exits with a zero status the test thinks everything is okay. /face-palm

P.S., This doesn't cause a problem on my OpenBSD 6.2 system apparently because I'm running it inside a VMware VM and the `zzz` fails with `zzz: cannot connect to apmd: No such file or directory`.

**Comment by kernigh** [comment]
There is a similar bug in `src/cmd/ksh93/tests/signal.sh`; it will run an external command `tst` if it exists. I verifed this by writing a command `tst` that plays music. I ran `meson test`, then heard music. (I heard at least 2 instances of the music in parallel.)

**Comment by krader1961** [comment]
FWIW, This problem is actually more subtle than it appears at first glance. The main problem is the definition of how autoloaded functions in `$FPATH` are resolved:

> FPATH The  search  path  for function definitions.  The directories in this path are searched for a file with the same name as  the  function  or command  when a function with the -u attribute is referenced and when a command is not found.  If an executable file with the name of  that command  is  found, then it is read and executed in the current environment.  Unlike PATH, the  current  directory  must  be  represented explicitly  by .  rather than by adjacent : characters or a beginning or ending :.

Notice that an external command found in `$PATH` is preferred over a autoloaded function in `$FPATH`. That is seriously FUBAR. The fish shell has saner behavior in this regard. Sadly the current behavior can probably never be changed. Not only making writing robust unit tests hard but also making using autoloaded functions in "the real world" hard. As long as `$PATH` includes a directory with a command of a given name it doesn't matter that there is an autoloaded function in `$FPATH`. Here is where I swear a lot.

**Comment by krader1961** [comment]
I fixed this with the refactoring of the unit tests to use a framework for running all the tests. See PR #481.
