### ISSUE TITLE
bin/lint can't find some headers when linting more than one file

### ISSUE THREAD

**Issue by kernigh** [att/ast#434]
bin/lint misses some -I flags, so IWYU and cppcheck can't find some header files. This happens if bin/lint is linting more than one file. bin/lint can't take more than one file in its arguments, so the only way to lint more than one file is to modify multiple files.

Given these commands:
```
$ echo >> src/lib/libast/misc/spawnvex.c
$ echo >> src/cmd/ksh93/sh/xec.c
$ bin/lint
```

Then IWYU and cppcheck report errors in xec.c about include files not found. If bin/lint checks xec.c by itself, then the errors don't appear.

I'm running OpenBSD 6.2 with fish 2.7.1, python3 version 3.6.2, meson 0.42.1, include-what-you-use 0.8 based on clang 5.0.0, cppcheck 1.80. Don't have oclint.

**Comment by krader1961** [comment]
Thanks for actually trying this utility script; especially since it requires installing the Fish shell. The problem is due to an invalid assumption I made when I wrote the *bin/partition_compile_db* helper command. Specifically, that the flags would be the same for all files being linted (which is true for the project for which I originally wrote this). I'll need to rethink how to do this efficiently in light of how the AST code is built.

BTW, @kernigh, how do I get the man pages for the standard utilities installed? I've never used OpenBSD before setting it up in a VM for this project and have had no luck figuring out how to get `man cmp`, for example, to show me that man page.

**Comment by krader1961** [comment]
P.S., Regarding my previous question, @kernigh, I've installed the `man-pages-posix-2013a.tgz` package and all the expected files are in */usr/share/man/man1*. Aha! I see that */etc/man.conf* is empty. Adding `manpath /usr/share/man` fixes the problem. Can't say that I'm much of a fan of an OS that can't even get such basic defaults right.

**Comment by kernigh** [comment]
@krader1961, OpenBSD has online manuals at https://man.openbsd.org/

To install the manuals, see ["File sets" in the OpenBSD FAQ](https://www.openbsd.org/faq/faq4.html#FilesNeeded). The manuals are in the _manXX.tgz_ file set (_man62.tgz_ for OpenBSD 6.2). The installer selects all the file sets by default, but one might have deselected manXX.tgz to save space or speed up the install. The FAQ says to reboot into bsd.rd (I would type `boot bsd.rd` at the `boot>` prompt), then choose Upgrade and add the file sets.

The manuals in `man-pages-posix` are from POSIX, not from OpenBSD. The command `pkg_add man-pages-posix` installs them in _/usr/local/share/doc/posix/man_, out of the default manpath. There's a readme in _/usr/local/share/doc/pkg-readmes/man-pages-posix-2013a_.

If you put manpath lines in _/etc/man.conf_, you lose the default manpath. You can add it back by copying the manpath lines from _/etc/examples/man.conf_.
