### ISSUE TITLE
Test applications written in ksh through CI

### ISSUE THREAD

**Issue by siteshwar** [att/ast#598]
We should setup CI to test applications that are written in ksh. For e.g. kshdb.

**Comment by rocky** [comment]
While you are waiting to hear back for other ksh programs to test, why not start with kshdb now since that's been a known source for finding ksh breakage. 

Working around what might be another ksh bug, (issue #610), I've just release 0.07 which currently passes all of its regression tests with the current git version of ksh, and SEGV's on Ubuntu's ksh93u+

Around 2011 kshdb worked and starting in 2012 or so it had been broken for the last 6 years. 

On the other hand, if there's no interest in having a debugger for ksh, that too would be useful to know so I won't spend time keeping this up to date. For POSIX shell debugging there still are the zsh and bash debuggers which by far have required less maintenance.

**Comment by siteshwar** [comment]
I have setup a cron job to trigger these tests once in a day on latest copr builds.

**Comment by rocky** [comment]
Many thanks. I greatly appreciate it. 

To reduce the possibility of changes to kshdb messing up ksh testing. I have just added tag  `att-ksh93v-testing` to the kshdb repository.
