### ISSUE TITLE
Undocumented `alarm` builtin -- whither its future?

### ISSUE THREAD

**Issue by krader1961** [att/ast#646]
While investigating why `read -t0.01` might not time out (see this PR [comment](https://github.com/att/ast/pull/645#discussion_r199972130)) I stumbled across the *src/cmd/ksh93/bltins/alarm.c* module which implements the undocumented `alarm` builtin. When I googled it I found only one relevant result: https://blog.fpmurphy.com/2008/12/mysterious-ksh93-alarm-builtin.html. Notice that was written in Dec 2008 and refers to ksh93s. The last sentence of the article is

> Use alarm with caution since Dave Korn has also stated that "alarm hasn’t been documented because it is not working in all cases."  The examples shown in this post were tested using ksh93 version s.

If a feature is that old and still undocumented it may be time to drop it. Or at least not enable it by default (which is currently the case) and add a "here be dragons" warning at the top of the module.

**Comment by krader1961** [comment]
No one has an opinion on the undocumented, probably broken, `alarm` builtin? If no one can argue for why it should be retained and documented I want to remove it.

**Comment by siteshwar** [comment]
This change broke one of our internal test cases. I could not get exact case history, but there is a public [e-mail thread](https://www.mail-archive.com/ast-users@lists.research.att.com/msg00972.html) and [bug](https://bugzilla.redhat.com/show_bug.cgi?id=1176670) about it. I am not in favor of reinstating this builtin, but since it was enabled by default we should document removal of it in changelog.

**Comment by krader1961** [comment]
CHANGELOG.md updated to note this undocumented command is no longer available.
