### ISSUE TITLE
Another bogosity in the SFIO subsystem, module sfnew.c

### ISSUE THREAD

**Issue by krader1961** [att/ast#655]
Again, cppcheck, tells us something isn't quite right:

```
[../src/lib/libast/sfio/sfnew.c:50] warning (uselessAssignmentPtrArg):
 Assignment of function parameter has no effect outside the function. Did you forget dereferencing it?
```

Which is from this block of code:

```
Sfio_t *sfnew(Sfio_t *oldf, void *buf, size_t size, int file, int flags) {
    Sfio_t *f;
    int sflags;

    SFONCE(); /* initialize mutexes */

    if (!(flags & SF_RDWR)) return NULL;

    sflags = 0;
    if ((f = oldf)) {
        if (flags & SF_EOF) {
            if (f != sfstdin && f != sfstdout && f != sfstderr) f->mutex = NULL;
            SFCLEAR(f, f->mutex);
            oldf = NULL;
        } else if (f->mode & SF_AVAIL) { /* only allow SF_STATIC to be already closed */
            if (!(f->flags & SF_STATIC)) return NULL;
            sflags = f->flags;
            oldf = NULL;
        } else { /* reopening an open stream, close it first */
        ....
    }
```

Note that `oldf` is not used anywhere else in the function other than the three lines above. And the local var `f` is completely superfluous. Furthermore, a few lines later is this statement:

```
    if (!f) { /* reuse a standard stream structure if possible */
```

Which should just be a `} else {` attached to the previous test for whether the `oldf` pointer is not NULL.

We need to drop the dependency on SFIO. The quality of the code is low and no one outside of the AST team knows how it works.

**Comment by krader1961** [comment]
FFS! There is an even bigger bogosity in *sfnew.c*. There is a code path which leads to `f` being NULL when we get to this statement which expects `f` to be a valid pointer:

```
if (!f->mutex) f->mutex = vtmtxopen(NULL, VT_INIT);
```

This is the "Fundamental function to create a new stream." according to its doc string. This sort of thing makes me wonder if there is any point in trying to keep the project alive. I can understand why the bug in issue #653 exists. That function isn't used and was apparently an enhancement that was never fully implemented and tested. But the `sfnew()` function is used and its correct behavior is critical. How the hell does this crap continue to exist decades after the code was merged?

**Comment by DavidMorano** [comment]
> We need to drop the dependency on SFIO. The quality of the code is low and no one outside of the AST team knows how it works.

I agree, but just for the record: 
+ SFIO seems to be very integrated into KSH, the removal of it would have to be carefully done
+ SFIO is currently a part of the published API for the interface to KSH built-ins, so removing SFIO would break compatibility with existing built-ins (I think I made some previous posts on possible ways to approach this when the time eventually comes)

> How the hell does this crap continue to exist decades after the code was merged?

:-)  I think that your own (unstated) guesses on this are probably correct.

**Comment by krader1961** [comment]
FWIW, I don't think there is a bug. A bug in this function would have been noticed by now. It is likely that an earlier version of the code was `if (!oldf)` for that second outer if. Then someone rewrote the logic but didn't notice it should be turned into an `} else {` clause attached to the earlier `if (f)`. And the dereference of a NULL `f` can't actually happen. Turns out this statement ensures that dereference never happens:

```
if (!(f = (Sfio_t *)malloc(sizeof(Sfio_t)))) return NULL;
```

**Comment by DavidMorano** [comment]
@siteshwar 
>tbh I don't think we can remove it. SFIO has to be kept as a dependency and if it has any bugs that should be fixed.

I think that it (SFIO) can be eventually removed, it is just that a little bit of thought will have to go into the new solution to accommodate the issue with the interface to built-ins.  It is not insurmountable. If it wasn't for built-ins, there would be no problem at all since there is no visibility of SFIO from outside of KSH normally.  

I love the AST people. I love KSH.  I loved AT&T Bell Laboratories. I worked there myself. I understood what the AST people were trying to do from about almost 30 years ago. We were brothers of sorts. But the SFIO package was a little bit (or more) poorly designed in my humble opinion and the actual code for it is extremely:

+ messy
+ old
+ unintelligible
+ messy (did I already mention this)
+ essentially unmaintainable
+ never was tested well to begin with
+ never was tested well throughout all of its years in service
+ not readily extensible for asynchronous operation
+ likely has bugs related to thread-safety (when compiled with thread-safety)
+ is an incredible pain to adapt for specialized uses in a polled environment
+ actually not really designed well for a polled environment
+ is total crap

I have probably written about as many KSH builtins as almost anyone else in the world, excepting maybe one or two of the AST people themselves (I have written about or over 125 KSH built-ins, several of them begin huge and complicated programs), and I have tried desperately to adapt SFIO to newer environments like multi-threading, asynchronous use, and polled use, but it (SFIO) is not very agreeable to use or change in these kinds of environments.

SFIO (like most all code packages) was designed for a certain purpose and for a certain time and mindset. It was designed in a time before mass and extensive asynchronous operation was required. It was also designed before code maintainability was more important than just about anything else, and ESPECIALLY more important than any stupid speed consideration.

Using SFIO places some hard restrictions on what can be done within built-ins. This mostly has to do with asynchronous and polled operations, so that is why few people besides myself are complaining loudly.  There were two major problems hindering modern asynchronous and multi-threaded use within built-ins and these were VMALLOC and SFIO.  Thanks very much (VERY MUCH) to Kurtis Rader, yourself, and maybe others, the VMALLOC problem is pretty much history now. It was hard but not insurmountable to get rid of VMALLOC. The same will be the case with SFIO. It might require a touch of very careful thought, but I do not think that it is totally out of the question to eventually get rid of it. Yes, maybe old KSH bullt-ins might be incompatible (for the most part), but I think that the world can survive that. Most KSH built-ins used in the world were probably shipped with KSH itself (written by the AST people), so there may not actually be as many KSH built-ins out in the wild as we may all fear. The eventual change of getting rid of SFIO from within the KSH code would just have to be carefully documented in the associated release notes.  With some careful removal of SFIO from KSH, the most likely only necessary change to existing KSH built-ins (still) using SFIO might be to add a call to |sfsync(3sfio)| just before the return of the built-in back to KSH. I think that this is both manageable and reasonable, and not very burdensome on built-in developers.  Eventually, like me, built-in developers will get rid of SFIO from within their own built-ins and the world will be a much better place for it!

No one is getting rid of SFIO from KSH any time soon, so let us not get too worked up (yet) about its removal.  The focus should be to get a very solid and as bug-free version of a new KSH available to the world as can be done. Getting rid of SFIO will be a future project for a second (at the very least) or subsequent major release of the new KSH.

Let me take this opportunity to publicly thank both Kurtis Rader and Siteshwar Vashisht for their herculean efforts in cleaning up KSH.  Your work on this is and will be historic even if it does not feel that way right now.  KSH needed some cleaning up in order to prepare it for a future world where new things can, might, and will happen in a shell. KSH did not have to be a frozen relic in history. In this regard, the vision of David Korn was correct. KSH just needed some cleaning up in order to prepare it for possible future extensions.  Actually all of the cleaning up to date has only been the very tip of the start of what could be a more extensive clean-up and modernization effort; but I do not want to scare anyone right now, so we can leave that sort of discussion as closed for now.

Special thanks very much again to both Kurtis Rader and Siteshwar Vashisht.

**Comment by krader1961** [comment]
Thank you, @DavidMorano, for that comment. There will definitely have to be at least one release before SFIO is removed. And the removal of SFIO will mean a major, backward incompatible, release. Which, given how much time has elapsed since the last major release should be acceptable. Including breaking compatibility with third-party plugins.

How difficult that job will be depends a lot on how much of the SFIO specific features, such as discipline functions, are used and for what purpose. There are parts of libast, most notably CDT, which are core to the behavior of ksh and thus will always remain. But I see no reason to think that is true of SFIO.
