### ISSUE TITLE
bogus NLSPATH handling

### ISSUE THREAD

**Issue by jelmd** [att/ast#66]
NLSPATH resolver bug needs to be fixed: see https://github.com/jelmd/ast/issues/1

**Comment by jelmd** [comment]
please pull https://github.com/jelmd/ast/commit/bcf9fb499bab90a66e81535854d73717a37158c0

**Comment by krader1961** [comment]
I vote no to merging the suggested fix.

Why is ksh93 still using the libast language translation functions? Rather than continuing to maintain and fix that code we should switch to the standard locale functions such as `gettext()` and the idiom of `printf(_("please localize me\n"));`. This would be another huge step in slimming down the ksh code base that has to be maintained by eliminating the need to maintain the AST message catalog code.

**Comment by jelmd** [comment]
Well, I _guess_, the initial idea was to not depend on non-libc/ non-ast libs and provide base for $'....' handling. Anyway, if you vote against merge, you should provide an alternative to fix the bug or tell, what needs to be fixed in the fix ;-)

**Comment by krader1961** [comment]
I did provide an alternative solution, jelmd. To wit: use the reasonably standard `gettext()` API and related tools. Also, your problem statement was just

> NLSPATH resolver bug needs to be fixed.

What bug? How can someone reproduce the problem? Why didn't you add a unit test?

And this comment in your fix suggests to me the fix is not reliable:

```
/* 'ksh93_tm' hopefully does not resolve to a regular executable file */
```

I realize English is not your native language but you continue to be willfully obtuse and obnoxious in your comments. Not just in this project bug also here: https://github.com/tensorflow/tensorflow/issues/13550. Most people are going to ignore you because of your abrasive style of interaction.

**Comment by jelmd** [comment]
Again, why do you read the subjects, only and not the problem description before making unqualified  comments again and again?

The bug description as well as test case are included in the issue comment 1! 

Wrt. "fix is not reliable": Can you read the issue description first and than ask, what you not understand?
I think it is pretty well explained, what happens and at least a ksh developer, who knows, how ksh's localization currently works, should understand it (even if it is not native/perfect English). And if so, one would realize, that the fix tries to circumvent the problem but can't fix it for all corner cases (here if a 'ksh93_tm' binary can be found via PATH), because this would break ksh behavior.

Wrt. to the last paragraph: plz do not talk about stuff you do not understand! Picking up some stuff w/o the context is a really bad behavior!

**Comment by krader1961** [comment]
We're going to drop use of the libast locale code as soon as possible. This will make `ksh` behavior consistent with other programs on a given platform. So there isn't much point merging a change for this obscure problem.
