### ISSUE TITLE
Integrate csbuild in CI

### ISSUE THREAD

**Issue by siteshwar** [att/ast#683]
`csbuild` is a tool to find defects introduced by new commits/pull requests. It scans for warnings between builds and reports any differences, it can be useful to avoid introducing any new defects. For example of it's usage see https://github.com/kdudka/curl/blob/csbuild/.travis.yml

**Comment by krader1961** [comment]
It looks like you're referring to this Linux [tool](https://www.systutorials.com/docs/linux/man/1-csbuild/). Does it even interact well with Meson? Given that we've worked hard to eliminate all the compiler warnings why not just just add `-Werror` to our compiler flags to treat any new warnings as fatal errors? That would be a lot more straightforward and work on platforms other than Linux.

**Comment by siteshwar** [comment]
> It looks like you're referring to this Linux tool. Does it even interact well with Meson?

Yes, this is the same tool. It should work with any build system. You can see a test build for it [here](https://travis-ci.org/siteshwar/ast/builds/403663234). Besides compiler warnings, it also uses `cppcheck` to detect new issues. The downside is that it does differential builds, so it will increase build times on travis.

We suppress certain warnings during build, so setting `-Werror` may not be the best option. I might be a bit biased to use `csbuild` as it was authored by @kdudka and we have been using it within Red Hat to find new defects in code, but I am open to hear arguments against it.

**Comment by krader1961** [comment]
I don't doubt that `csbuild` is incredibly useful for a company like Red Hat which has to continuously build and test packages they don't directly maintain. And therefore want to have an easy way within the context of their CI mechanism of detecting possible problems via the presence of new compiler and `cppcheck` warnings. But AFAICT it would add little or no benefit to this project and a lot of cost.

> it also uses cppcheck to detect new issues.

I'm not convinced that is worth the cost of doubling the build time on Travis. I've made it drop dead simple to run `cppcheck` and `oclint` and `iwyu` via the `bin/lint` script. I'd prefer to focus on eliminating the current cppcheck warnings so that differential checks of its output aren't necessary. Either there are warnings or there are none. If there are warnings then your change, or a recent change, introduced them. I don't think that warrants breaking the build on Travis or making it more expensive.

> We suppress certain warnings during build, so setting -Werror may not be the best option.

How does `csbuild` address suppressed warnings? I see nothing in its man page that even implies it would magically stop suppressing warnings we've deliberately suppressed. In fact if it did so I would consider that wrong behavior. The advantage of `-Werror` is we can enable it on every platform we test on. Not just those that have `csbuild` installed.

**Comment by kdudka** [comment]
On Saturday, July 14, 2018 1:45:34 AM CEST Kurtis Rader wrote:
> Given that we've worked hard to eliminate all the compiler warnings why not 
> just just add `-Werror` to our compiler flags to treat any new warnings as
> fatal errors?

Problem of -Werror is that the build stops prematurely if a warning is 
detected.  Moreover, if you build in parallel, it is undefined how many 
warnings/errors are reported before the build stops.

Also using -Werror makes pressure on developers to fix reports which they
are not competent to fix, resulting in new real bugs being introduced while 
trying to fix theoretical bugs.

Please have a look at the following example of a potential disaster caused
by enforcing -Werror=format-security in Fedora builds:

https://bugzilla.redhat.com/1025257#c7

**Comment by kdudka** [comment]
On Saturday, July 14, 2018 9:07:14 PM CEST Siteshwar Vashisht wrote:
> The downside is that it does differential builds

Not sure if a downside really but differential builds are a strictly optional 
feature of csbuild.  You can use csbuild for non-differential builds, too.

**Comment by siteshwar** [comment]
> How does csbuild address suppressed warnings? 

Just do a build without suppressing warnings. For e.g.

```
csbuild --git-commit-range ${TRAVIS_COMMIT_RANGE} -c 'meson -Dbuild-api-tests=false build; ninja -C build'
```

**Comment by siteshwar** [comment]
@krader1961 I should mention that I don't plan to plug `csbuild` into existing jobs. Instead I will introduce a separate job in build matrix to run `csbuild`. We can do it as an experiment and if we face any issues, we will just remove that job.

**Comment by krader1961** [comment]
> Problem of -Werror is that the build stops prematurely if a warning is detected. 

Yes, but in practice that should not be a problem. We would add that flag only to the Travis config. Local builds would not use that flag thus allowing the user to see all the warnings from a given compilation unit rather than just the first. If they then open a PR with outstanding warnings I don't really care if the Travis build log shows me just the first one or all of them. All I need to know is the author didn't care enough to deal with obvious problems with their change.

> differential builds are a strictly optional feature of csbuild.

Okay, but I thought that was required to detect the presence of new warnings? And while you don't have to do a full build don't you still have to do the `meson` config step twice. First with the current commit and then with the previous commit in order to run `cppcheck` twice so as to determine which cppcheck warnings, if any, are introduced by the current commit?

> https://bugzilla.redhat.com/1025257#c7

That example doesn't surprise me too much and more than anything illustrates the need for code reviews. I've already cataloged a large number of mistakes in the ksh code that is worse than that example. What's interesting about that example is the transformation applied to the first `sprintf()` is correct, safe, and would have silenced the warning. What leaves both of us scratching our heads is why they mindlessly applied the same transformation to the other `sprintf()` calls which presumably were not causing warnings.

> We can do it as an experiment....

Okay by me, @siteshwar. I'm still not convinced this is worth the cost __in the context of this project__ as opposed to internal builds by a distro maintainer like Red Hat. But I'm not going to veto your doing the work and obtaining objective data on the costs and benefits.

**Comment by krader1961** [comment]
I just checked and clang and gcc both continue parsing the code and emitting errors with `-Werror`. It only stops when it reaches the limit which defaults to zero meaning unlimited. So even on Travis we would still see all the warnings/errors.

**Comment by krader1961** [comment]
> We suppress certain warnings during build, so setting -Werror may not be the best option.

As I mentioned in PR #692 that isn't true. It turns out the `CFLAGS` env var only affects the compilations during the `meson` build config phase. It does not affect the compiler flags used when compiling the source via `ninja`. And since we have eliminated all the compiler warnings those `-Wno-...` flags wouldn't do anything even if they were used when building the code.

**Comment by kdudka** [comment]
On Tuesday, July 17, 2018 1:02:47 AM CEST Kurtis Rader wrote:
> Yes, but in practice that should not be a problem. We would add that flag
> only to the Travis config. Local builds would not use that flag thus
> allowing the user to see all the warnings from a given compilation unit
> rather than just the first. If they then open a PR with outstanding
> warnings I don't really care if the Travis build log shows me just the
> first one or all of them. All I need to know is the author didn't care
> enough to deal with obvious problems with their change.

Only if you get the same errors/warnings for both local and Travis CI builds.

> > differential builds are a strictly optional feature of csbuild.
> 
> Okay, but I thought that was required to detect the presence of new
> warnings? And while you don't have to do a full build don't you still have
> to do the `meson` config step twice. First with the current commit and then
> with the previous commit in order to run `cppcheck` twice so as to
> determine which cppcheck warnings, if any, are introduced by the current
> commit?

This is really up to you.  You can configure csbuild to invoke full build just 
once and then rebuild only files changed by the commits in question.  It works 
well for detecting newly introduced defects (assuming the build system itself 
works reliably, which I believe meson/ninja does).

On the other hand, the optimized approach will not work reliably for reporting 
fixed defects, or finding "bad" commits by git-bisect.

**Comment by kdudka** [comment]
On Tuesday, July 17, 2018 1:20:54 AM CEST Kurtis Rader wrote:
> I just checked and clang and gcc both continue parsing the code and emitting
> errors with `-Werror`. It only stops when it reaches the limit which
> defaults to zero meaning unlimited. So even on Travis we would still see
> all the warnings/errors.

It does not make any sense to me.  I thought that preventing the build from 
completing was the only purpose of the -Werror* compiler flags.

**Comment by kdudka** [comment]
On Tuesday, July 17, 2018 6:17:23 AM CEST Kurtis Rader wrote:
> As I mentioned in PR #692 that isn't true. It turns out the `CFLAGS` env var
> only affects the compilations during the `meson` build config phase. It
> does not affect the compiler flags used when compiling the source via
> `ninja`. And since we have eliminated all the compiler warnings those
> `-Wno-...` flags wouldn't do anything even if they were used when building
> the code.

You can use csbuild to inject arbitrary compiler flags fully transparently.  
It uses a compiler wrapper (cswrap), which does not really care which build 
system you are using and which environment variables the build system is 
sensitive to.  It worked even with the original build system of ksh ;-)

**Comment by krader1961** [comment]
> I thought that preventing the build from completing was the only purpose of the -Werror* compiler flags.

Correct. Even if the unit tests would otherwise pass we don't want to allow changes which introduce compiler warnings. Perhaps I misunderstood what you meant by "Problem of -Werror is that the build stops prematurely if a warning is detected." I took that to mean you were concerned the compiler would stop providing feedback about other problems with the code when the first warning, now treated as an error, was reported. I was pointing out the compiler will still report all the problems it finds. Using `-Werror` is simply an easy way to cause any unwanted lint from creeping in by treating the issue as a compilation error. That this keeps unit tests from running isn't an issue in my opinion.

**Comment by krader1961** [comment]
See my latest comments on PR #697. I am now a more strong thumbs down on integrating `csbuild` into this project. I can see how that tool would be useful in other contexts. But in the context of this project it adds a lot of cost with little to no benefit. We have full control of this project. If we want to enable a compiler option like `-Wempty-body` we can easily do so after fixing the existing violations. As I wrote in that PR:

I also downloaded the raw log file from my latest change and summarized the warnings from csbuild:

```
$ sed -ne 's/^.* \[\(-W[a-zA-Z-]*\)\].*$/\1/p' log.txt | sort | uniq -c
  90 -Wcast-function-type
  18 -Wempty-body
 283 -Wmissing-field-initializers
 291 -Wsign-compare
   2 -Wunused-but-set-parameter
```

Seems like it should be straightforward to fix/suppress those warnings. Then add -Wall (which is what csbuild is doing when invoked with -w1) and have the benefits of csbuild without the cost. If we really don't want code to be added which causes those warnings then we should just fix the existing instances and add `-Wall` to our config. We can do so incrementally as I did with commit 15f8de6.

**Comment by krader1961** [comment]
I added the `-Wextra` flag to the build. Which is what csbuild apparently uses despite my earlier misstatement in PR #697 that it uses `-Wall`. I have disabled two of the warnings `-Wextra` implicitly enables on GCC because they result in far too many false positives for this project. Especially with respect to GCC8's `-Wcast-function-type`.  I did remove several of the simpler, pointless, function casts by eliminating the need for those casts. TBD is what to do about the casts in *src/cmd/ksh93/bltins/math.c*. I have also fixed all the other warnings under -Wextra. Coupled with our use of -Werror integrating `csbuild` no longer adds any value AFAICT even if you ignore its costs. So I think this can be closed.

**Comment by krader1961** [comment]
Another objection to incorporating `csbuild` into our Travis CI builds is that the compiler warnings it enables will probably not be enabled in local builds. We should strive to have Travis CI and local compiler behavior be as similar as possible so that someone contributing to the project is likely to see the problem before they create a PR (i.e., a pull-request). Obviously the exclusion of `csbuild` won't account for differences between clang vs gcc, not to mention different versions, of the build environments. Nonetheless, I don't see a compelling reason to introduce yet another reason why the Travis CI results might differ from what someone sees on their local system(s).

**Comment by siteshwar** [comment]
@krader1961 Ok, I am fine with not integrating `csbuild` in upstream. The main reasons are:

- We plan to eliminate (almost) all warnings from build process.
- We have limited resources in Travis that are not sufficient to perform thorough static analysis scans.

We can perform more thorough scans through Red Hat's internal static analysis service, so I am going to hook it to upstream. It won't be possible for us to share it's results publicly, so I will keep an eye on it and will follow up if I see any issues.
