### ISSUE TITLE
Expect based tests have transient failures that can be hard to understand

### ISSUE THREAD

**Issue by siteshwar** [att/ast#812]
Related log from failing test:

```
193/194 emacs.exp                               OK       2.32 s 



--- command ---

SHELL='/Users/travis/build/att/ast/build/src/cmd/ksh93/ksh' LD_LIBRARY_PATH='/Users/travis/build/att/ast/build/src/lib/libast:/Users/travis/build/att/ast/build/src/lib/libcmd:/Users/travis/build/att/ast/build/src/lib/libcoshell:/Users/travis/build/att/ast/build/src/lib/libdll' LIBSAMPLE_PATH='/Users/travis/build/att/ast/build/src/lib/libdll/libsample.dylib' /Users/travis/build/att/ast/build/src/cmd/ksh93/ksh /Users/travis/build/att/ast/src/cmd/ksh93/tests/util/run_test.sh emacs.exp

--- stdout ---

<I> run_test[73]: TEST_DIR=/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/ksh.emacs.exp.XXXXXXX.YPgUDde1

<I> run_test[203]: Iteration 1 of interactive test 'emacs.exp' failed

--- stderr ---

<E> run_test[122]: Stdout for emacs.exp had unexpected differences:

--- /Users/travis/build/att/ast/src/cmd/ksh93/tests/emacs.exp.out	2018-08-26 22:15:16.000000000 +0000

+++ emacs.exp.out	2018-08-26 22:21:41.000000000 +0000

@@ -18,15 +18,3 @@

 ctrl-k deletes characters to end of line

 ctrl-w kills from cursor to mark

 ctrl-y yanks back item to the line

-alt-< fetches least recent history line

-ctrl-r reverse searches history for a previous command

-ctrl-o executes current history entry

-ctrl-o executes current history entry and retrieves next history entry

-alt-. inserts last word from previous command

-alt-_ inserts last word from previous command

-alt-* generates file name completions

-tab generates command or file name completions

-alt-= generates file or command name completions

-alt-ctrl-v generates version number

-alt-# appends '#' to beginning of line

-alt-# appends '#' to beginning of line and puts it in history

<E> run_test[143]: Stderr for emacs.exp should have been empty:

timeout

    while executing

"error $msg"

    (procedure "abort" line 2)

    invoked from within

"abort "timeout""

    invoked from within

"expect -re "^set -o emacs$" {

    puts "alt-< fetches least recent history line"

}"

    (file "/Users/travis/build/att/ast/src/cmd/ksh93/tests/emacs.exp" line 251)


-------
```

They are probably failing due to timing issues.

**Comment by krader1961** [comment]
I've never seen this failure. Can you add the missing *interactive.tmp.log* or provide a link to the Travis results?

And, yes, timing issues are an even bigger challenge with `expect` based tests than it is for the other tests.

**Comment by siteshwar** [comment]
For e.g. it failed [here](https://travis-ci.org/att/ast/jobs/420874292).

**Comment by krader1961** [comment]
I was perplexed by the original comment which seemed to say the test succeeded. And upon closer inspection I see it did succeed on the second attempt. Only the first attempt failed:

> <I> run_test[203]: Iteration 1 of interactive test 'emacs.exp' failed

Note that it completed in 2.32 seconds rather than the 0.3 seconds which would be expected. That's because of the two second `expect` timeout that caused the first iteration to fail. We try to run each `expect` based test multiple times, and not in parallel with other tests, precisely because they are so sensitive to the state of the platform. On VMs, like those provided by Travis, there are often brief periods when the system may be overcommitted that can cause an operation to take longer than expected.

Without the `interactive.tmp.log` there's no way to know exactly what happened on that first iteration other than that the expected output from the [esc]< wasn't seen. I deliberately only dump that log file if all iterations fail since it can be quite lengthy. To help with debugging these types of transient, essentially harmless, failures I'll amend the test runner to dump the entire `expect` log file on the final iteration and only the last few lines on preceding iterations.

**Comment by krader1961** [comment]
Also, transient failures like in this issue can occur on any platform. The reason you're more likely to see them on our Travis macOS platform is that those systems are more likely to be overcommitted than the Linux boxes. That at least is the experience of the `fish` shell project from which I borrowed some of this test harness. Back when I was contributing to that project we would see transient failures on macOS at a rate roughly three to four times as often as the Linux VMs.

**Comment by siteshwar** [comment]
It failed again [here](https://api.travis-ci.org/v3/job/421886837/log.txt).

```
<I> ========== STARTING TEST AT LINE 283 ==========

<I> send {echo hello}

<I> send \e

<I> send h

<I> send i

<I> send x

<I> send \e

<I> send {\x0c}

<I> send i

<D> entering expect

<D> timeout; buffer=echo hello^[hix^[^Liecho hell\x08\r\n\rKSH PROMPT:10: 

<D> expect returned code 1

timeout

    while executing

"error $msg"

    (procedure "abort" line 2)

    invoked from within

"abort "timeout""

    invoked from within

"expect -re "echo helxlo" {

    puts "h moves cursor backward one character"

}"

    (file "/Users/travis/build/att/ast/src/cmd/ksh93/tests/vi.exp" line 290)
```

**Comment by krader1961** [comment]
Notice the first iteration failed on line 260, the second 276, the third 290; i.e., a different test each time. The Travis macOS VMs are overcommitted. You can see from the `expect` debug log `buffer` entries that it appears as if the ksh process has stopped responding, probably because it was swapped out. We can try tweaking timeouts but it's probably better for our sanity to just disable these tests on Travis macOS.

**Comment by krader1961** [comment]
@siteshwar What do you want to do? Based on my experience contributing to the fish shell project I think it is hopeless to expect the `expect` based unit tests to not be flakey on Travis macOS. That project simply accepts that there will be an annoying percentage of flakey failures of these tests on Travis macOS.

I am not seeing this failure mode on either of my macOS systems (one a Vmware VM and one on bare metal). We could expend a lot of effort trying to reduce the flakiness without much improvement based on my experience with the fish shell. So it seems like we either live with these failures or omit these tests on Travis macOS.

**Comment by siteshwar** [comment]
@krader1961 Can we use some workaround to run `expect` based tests only if system is not under heavy load ? In case if a system is under heavy load just skip the tests by printing a message.

**Comment by krader1961** [comment]
I don't know how the Travis macOS environments are managed. Presumably they're virtualized using VirtualBox, Vmware, or something similar. Which would mean we don't really have any insight into how busy the underlying hardware is. We could experiment with `iostat` to see if what it tells us about the load average is helpful but I'm skeptical that will allow us to make an informed choice. If we try that approach I recommend doing it after all three iterations have failed and using the data to decide whether we report the failure or ignore it.

**Comment by krader1961** [comment]
There's an obvious, simple, heuristic we can use to deal with this. It's based on the observation that when these fail due to the system being overloaded each iteration tends to fail a different test. On the other hand real bugs involving interactive behavior tend to manifest in a deterministic manner. So after all iterations have failed simply test that no two failures involved the same test. If that's true pretend the test passed.

**Comment by krader1961** [comment]
Okay, this should be fixed. I verified on my macOS VM and Travis that flakey failures due to the system being overloaded are ignored and real, reproducible, failures are still caught.
