### ISSUE TITLE
Remove the "alpha" branch (and others too)?

### ISSUE THREAD

**Issue by krader1961** [att/ast#82]
The `alpha` branch contains only two commits and both are merged into the `beta` branch. This project does not currently have a release process defined. While it is possible we might define a process that includes an `alpha` branch that seems unlikely. More importantly the current `alpha` branch is stale and creates confusion. I would like to remove it. I'm wondering what @siteshwar, @dannyweldon, and others think.

There is also the `rhbz1503922` branch which includes one change merged by @siteshwar less than a day ago but otherwise seems to be identical to the `beta` branch. What is the purpose of that branch? Should it be a public branch of this repo or a private branch of an individual's fork?

The `travis-test` branch looks like another candidate for removal.

And, finally, there is the `gh-pages` branch which appears to delete more than it adds. What is the purpose of that branch? Should any of its changes be merged into the `beta` branch? Regardless, `gh-pages` should also be removed as soon as possible.

**Comment by krader1961** [comment]
It looks like the `rhbz1503922` branch is in response to this Redhat bug report: https://bugzilla.redhat.com/show_bug.cgi?id=1503922

It seems preferable to me that personal (or company specific) branches of that nature are not visible in the public project until a PR has been created.

**Comment by kdudka** [comment]
Not that I was asked but I fully support the proposed cleanup.  ```gh-pages``` is a branch that Github creates by default as a place to maintain project's web page (it is not intended for source code at all):

https://help.github.com/articles/what-is-github-pages/

If it is not used or maintained, I think it should go away, too.

**Comment by siteshwar** [comment]
I wanted to push ```rhbz1503922``` into my github fork but by mistake pushed it into the upstream. I have removed it now.

**Comment by siteshwar** [comment]
I have removed ```travis-test``` branch too as it has been merged into ```beta``` branch already. 

Regarding other branches :

* We can merge ```beta``` into ```master``` and do the development in master.
* Remove both ```alpha``` and ```beta``` branches. Commits from ```alpha``` and ```beta``` branches can be tagged with respective git tags if required.

I also started a discussion on [mailing list](https://www.mail-archive.com/ast-developers@lists.research.att.com/msg01979.html) regarding this change.

**Comment by kdudka** [comment]
On Friday, October 27, 2017 10:00:25 AM CEST Kamil Dudka wrote:
> ```gh-pages``` is a branch that Github creates by default as a place to
> maintain project's web page (it is not intended for source code at all):

I forgot to link the actual project page produced by the gh-branch:

https://att.github.io/ast/

**Comment by krader1961** [comment]
@kdudka, Thanks for the explanation regarding the `gh-pages` branch. Now that I've actually fetched that branch and checked it out it's clear why the Github web UI showed that 99.9% of the commits to that branch consisted of deleting all the content found in the `master` branch. I'm ambivalent about retaining it. We'd probably be better served by improving the *README.md* document and deleting that branch. On the other hand it doesn't cost us anything to keep it and we'll probably never have a reason to change it. If we decide to keep it I'd like to add your explanation for its existence to the wiki or a *CONTRIBUTING.md* document.

Also, I notice that static landing page takes advantage of magic URLs to make it easy for someone to download the source from the `master` branch; e.g., https://github.com/att/ast/tarball/master.

**Comment by krader1961** [comment]
@siteshwar, It seems like we should bite the bullet and merge `beta` into `master` then delete both `beta` and `alpha`. Yes or no? It's not clear that we need to worry about open pull-requests since git doesn't really care if the branch the PR was based on no longer exists. We just need to make a new line in the sand.

**Comment by siteshwar** [comment]
I am fine with merging ```beta``` into ```master```.

**Comment by qbarnes** [comment]
`master` should be treated like it's stable.  It should just be the most active development and test branch.

I would expect when a tagging policy is defined that there will need to be tags like `alpha-20171111` and `beta-20171023` marking when those releases are cut for public evaluation and once created will never move.

I would expect there to also need to still need `alpha` and/or `beta` branches, but those branches would have to be actively maintained by their designated owners who would cherry pick commits off of `master` guided by for their individual development efforts. But those branches shouldn't exist until  such time there are assigned owners/maintainers for such branches and have stated policies.

**Comment by jelmd** [comment]
A strong **NO GO** from my side.

Because the repo is the **'ast'**, the _master_ branch should contain _ALL_ the ast stuff and not only what is left for ksh. Therefore _beta_ should NOT be merged into _master_ on a as is base.

Instead only the "non-cleanup", i.e. bug-fix and new-feature commits from _beta_ should be cherrypicked into the master. All others/remaining ones should be merged into the ksh-master sub branch, which gets branched from _ksh-master_ (no matter in which repo it actually lives).

It looks like the development cycle @ATT was more or less sequential, i.e.  once a release has been made, this release got the alpha for the next version, at a certain point this was declared to be the beta version, got fixes, ... and finally declared as release. After that the cycle started again. Thus merging _alpha_ is not needed (already included in _beta_: commit 7e89f11), can be deleted ad hoc.

So IMHO a better way to go would be:

1. delete _alpa_ branch
1. tag master 'v2012-08-01-release' (3f54fd6) to be able to find it the old way
1. tag master '93.21.0.0.0.0.0' (3f54fd6) - semantic versioning
1. cherrypick from _beta_ into _master_
    1. merge 7e89f11
    1. tag it 'v2013-10-10-alpha'
    1. tag it '93.21.0.0.0.1.0'  (the 1st alpha based on 93.21.0.0.0)
    1. merge 9bc6abf
    1. tag it 'v2014-12-24-beta'
    1. tag it '93.21.0.1.0.0.0' (the 1st beta based on 93.21.0)
    1. merge c506cb5
    1. tag it 'v2016-01-10-beta'
    1. tag it '93.21.0.2.0.0.0' (the 2nd beta based on 93.21.0)
    1. merge/cherrypick all bug-fix and new-feature commits, but *NOT* "cleanup" commits
1. tag master 'ksh-split'
1. branch 'ksh-split' into _ksh-master_
1. branch _ksh-master_ into _ksh-master-cleanup_
1. cherrypick from _beta_ remaining aka "cleanup" commits into _ksh-master-cleanup_
1. delete _beta_ branch

Now all "cleanup" aka evtl. "new build system" PRs should go into _ksh-master-cleanup_. bugfixes as well as new features PRs may go to _ksh-master_, which should IMHO seen as the beta branch, which gets occasionally a release tag. Radical/bigger changes, really strange stuff/playgrounds or completely new features like the "ksh-cleanup" should be considered as "alpha" and should have their own branch for incr. PRs, should always be rebased on _ksh-master_ before the merge into it occurs.

So once ksh-master-cleanup maintainers are sure, that this branch does not break anything, should be beta tested, they can merge it back to _ksh-master_ and delete the _ksh-master-cleanup_ branch.
Meanwhile others may still provide/be able to work on _ksh-master_ or _master_ as usual.

Also this allows vendors to track changes much better (and probably as expected) and sort out, what they need.

The suggested new versioning schema is probably clear - follows semantic versioning and github behavior, how to display them (order):
1. major # (ksh "birthday", i.e. 88|93  ;-) )
1. minor # (u == 21st char in alphabet)
1. patch level # (old no prefix => 0, '+' => 1 ; now allows much more frequent patch releases w/o confusion)
1. beta # (after certain bug fixes and optionally alpha branch merge, maintainers may think, it is the time to advertise a new beta version: at this time this number gets incremented)
1. beta patch level # (betas usually get also some fixes and early adapters wanna get updates, have a human readable numbers to check ...)
1. alpha # (can be used to tag merges of "alpha" branches)
1. alpha patch level # (can be used to tag a patch set merge from an already merged, but still living alpha branch)

In general, if {major,minor,beta,alpha} # gets incremented, all digits following it get reset to '0'.

**Comment by jelmd** [comment]
NOTE wrt. versioning schema: We could also leave digits 6 and 7 for vendors to be able to tag their own changes properly and use `-feature-name` instead of them (-* implies alpha), because wrt. feature driven development alpha version nums are IMHO not that useful.

**Comment by krader1961** [comment]
The reality, regardless of whatever @jelmd thinks, is that 99.9% of people looking at this project are only interested in `ksh` (i.e., the Korn shell command) AFAICT. If you disagree please provide links to projects which use non-ksh portions of this project. As a grey beard (I was born in 1961) I appreciate old software but that is not sufficient to keep it alive.

**Comment by jelmd** [comment]
So why not create a separate repo?

**Comment by krader1961** [comment]
> So why not create a separate repo?

@jelmd, I am curious what your relationship is to this project. Were you a member of the AT&T AST team? Or are you just a fan due to the use of the code at the University you attended? Why are you so interested in trying to keep alive code that, for whatever reasons, has been rejected by the marketplace?

@jelmd, The `master` branch has not been updated since it was created two years ago. I knew the proposal to focus this repo on the `ksh` command would be controversial. As a grey beard (I starting programming in 1976) I greatly appreciate the work of the AT&T team working on the `AST` code and think it a shame that some of that code, like the SFIO library, was not widely adopted. But the reality is that today almost no one cares about anything from that work other than the Korn shell.

Note that `ksh` is still my preferred POSIX compatible shell. It may be too late to make `ksh` the preferred alternative to `bash`. But I'd like to at least make it a reasonable alternative to `zsh` (which I hate for its kitchen sink approach) and every other POSIX compatible shell. The way to ensure `ksh` remains relevant is to focus this repo on its maintenance and relegate maintenance of all the other `AST` code to second class status.

**Comment by dannyweldon** [comment]
I originally also wanted them split, but I think having them in the same repo simplifies sharing commits between branches if someone wants to take some of your changes and apply them back to the old code, which is essentially what @siteshwar has already done.  BTW, att/ksh is currently hosting a generic github pages repo, so it would at least need a readme created to direct users to where the real code lies and it also has a couple of issues open for ksh.

**Comment by kdudka** [comment]
What about creating a separate branch or tag to make the the pre-cleanup state of the source tree easier to find?  Would that work for you @jelmd?

Nevertheless, keeping the master branch just for the development of ksh sounds perfectly reasonable to me...

**Comment by jelmd** [comment]
the default (usually master) branch should cover the whole software, not only a single piece. If the default branch gets reduced to just ksh, all other software in there gets buried/hidden. People will never get the chance to use it, pick up its ideas, because they do simply not know, that it is there.

@krader1961 underlines again and again, that he does not want to maintain all the other ast stuff, but ksh only (which is IMHO ok), and the ongoing work shows, that it doesn't care at all about the SW in the other trees and above it. So it is not logic to burn down all the other stuff, just to get a `master` branch with ksh, only. Instead it makes much more sense to fork the target (ksh) into a separate branch or new repo and leave _ALL_ other stuff untouched, give other people the opportunity to catch up, revive it. And even when @krader1961 says, that in his very own opinion/little world no-one is using it, this means nothing - the opposite has been proven already  ([see ast-developer ML](https://www.mail-archive.com/ast-developers@lists.research.att.com/msg02011.html)). So we do not burn books, just because we have no idea, how they get/will be used, do not understand, what is written in there or just because they are "in the way", do not reproduce our own opinion about things or are simply old, do we?

BTW: there are some examples, where SW git split and never got together again, e.g. StarOffice and LibreOffice. Even if one would be a branch of the other, it is basically impossible/too much work, to sync patches ... From what I've seen so far, I guess this will happen here, too. I.e. sooner or later it comes to the point, where both branches diverged so far, that merging back stuff implies the same hard work, no matter, whether the other tree is actually a branch or a separate repo. Therefore I think, a separate ksh repo makes much more sense, gets krader1961 his own master tree and is easier for all to track progress in both "projects". We already have examples, where @krader1961 tells people, that ast aka non-ksh related issue gets not resolved. IMHO if he does not care about the full ast tree, he shouldn't make such statements - tomorrow, or in 1 month, or a year, or decade another smart developer may step in and continue working on the ast or parts of it, who knows ... So one more reason to split up into a 2nd repo and getting it clean "from the beginning"...

**Comment by krader1961** [comment]
Does anyone else have an opinion? The `beta` branch is already well on its way to being a `ksh` only branch. The `master` branch hasn't been updated in two years. We are really close to the point where it will be impractical to apply changes from the `beta` branch that affect the `ksh` code to the other branches. And once we have run the code through tools like `clang-format` and `oclint` it will be impossible to do so --- even with a huge amount of manual effort.

Anyone wanting to work with the non-ksh AST code can still do so and we should ensure the main *README.md* document clearly and prominently explains how to do so. The question now is whether we merge `beta` into `master` and continue working on ksh there or rename `beta` to `ksh`. If we do the latter it probably makes sense to merge `2012-08-01-master` to `master` and remove the former. I prefer merging `beta` into `master` because that will result in fewer mistakes being made and make it clearer to everyone that ksh is being actively maintained. If someone a decade from now wants to "step in and continue working on the ast or parts of it" they will still be able to do so.

**Comment by kdudka** [comment]
On Monday, November 20, 2017 3:48:20 AM CET Kurtis Rader wrote:
> And once we have run the code through tools like
> `clang-format` and `oclint` it will be impossible to do so --- even with a
> huge amount of manual effort.

Please do not reformat the code.  We need to backport fixes for Red Hat 
Enterprise Linux 6 and 7, which continue to be supported for a couple
of years from now.  Each change of code that is not a bug fix complicates
our work significantly.

**Comment by jelmd** [comment]
As said, ast-ksh != ast and since you already said, that merge backs are unlikely, fork it to a separate repo (e.g. ast-ksh) or something like this, but *do not touch the master*!

**Comment by krader1961** [comment]
> Please do not reformat the code.

The problem with that, @kdudka, is that the current state of the code makes it hard to read, understand, and thus maintain. If ksh is going to remain relevant we need to bring it into the 21st century. If that causes some pain for legacy distros like RHEL 6 I think that is a reasonable trade-off. 

I wish I hadn't used such hyperbolic language in my previous comment. Reformatting the code only means you won't normally be able to simply do a `git cherry-pick`. You'll have to manually apply the logic of the fix to your fork of the code. But that should still be relatively straightforward most of the time since I'm not proposing refactoring the code. If we don't do things like reformat the code to a consistent style, deal with all the compiler and lint tool warnings, drop support for pre-ANSI C compilers, improve the build process, etcetera then no one will want to touch the code to make it better and port it to new platforms like [Haiku](https://www.haiku-os.org/).

I think it's too late to think that `ksh` can become as, or more, popular than `bash`. But it would be nice if it at least supplanted alternatives like [mksh](https://www.mirbsd.org/mksh.htm) and `zsh` (which I hate with a passion).

**Comment by krader1961** [comment]
Also, @kdudka, note that my previous job was a level three Linux support engineer at IBM. Mostly doing things like kernel crash dump analysis for customers running RHEL and SLES distros. Before that I did the same thing for Sequent Computer Systems DYNIX/3 and DYNIX/ptx operating systems. So I am intimately familiar with the challenges of supporting distro releases that may be in their EOL phase.

**Comment by krader1961** [comment]
@jelmd, You can maintain your own fork. You have failed to make a convincing argument for "do not touch the master!" in this project. You wrote "he does not want to maintain all the other ast stuff, but ksh only". That is true. While I appreciate the work by the AST team, especially with their ground breaking SFIO and UWIN code, anything not directly relevant to `ksh` is dead history as far as I can tell. I am interested in keeping `ksh` a relevant shell. Anything that gets in the way of that goal needs to be removed.

**Comment by krader1961** [comment]
Closing this issue since we've gone ahead and merged the `beta` branch into `master`, dropped the `alpha` branch, and have decided that the `master` branch will be focused solely on the `ksh` command.
