### ISSUE TITLE
Remove feature test to check if mmap should be used

### ISSUE THREAD

**Issue by siteshwar** [att/ast#84]
This [iffe feature test](https://github.com/att/ast/blob/0fa99a9db97f0b3db5e4f2363c461c3dd4f50f3e/src/lib/libast/features/mmap#L206) results in non-determinstic builds, because it [compares loop execution times at build time](https://github.com/att/ast/blob/0fa99a9db97f0b3db5e4f2363c461c3dd4f50f3e/src/lib/libast/features/mmap#L302). I believe it can be removed and we can choose to always use ```mmap```.

**Comment by siteshwar** [comment]
Also, most of the feature tests from same file should be reviewed and removed if needed.

**Comment by krader1961** [comment]
Agreed. Make it so. Also note that even if it decides that mmap is slower (which should never be the case so the test seems dubious) it still decides to use mmap:

```
printf("#define _mmap_worthy	2	/* mmap worse than read on 64Ki buffers -- use it anyway */\n");
```

The `map_anon` and `map_devzero` tests can also be removed. I can't recall the last time I heard about an OS that supported `mmap()` but not the `MAP_ANON` flag. Which means we don't need to explicitly test that `MAP_ANON` is supported and we don't need to test the fallback of mapping `/dev/zero`.

**Comment by krader1961** [comment]
Also, this entire feature test is only there to support the AST malloc and sfio implementations. Both of which should be replaced with the libc malloc and stdio functions.

**Comment by krader1961** [comment]
Notice this [broken block of code](https://github.com/att/ast/blob/beta/src/lib/libast/vmalloc/vmdcsystem.c#L385) related to use of `mmap()`:

```
#if _std_malloc
        if((_Vmassert & VM_native) && (addr = mallocmem(vm, caddr, csize, nsize, disc)))
       {       GETMEMUSE(mallocmem, disc);
                return (Void_t*)addr;
#endif
```

Hint: It's missing the closing `}`. I noticed this because I thought I would try to build this code with `_std_malloc` defined since, as I mentioned earlier, it would be better if we used the OS provided libc functions for memory management as they are generally highly optimized and extremely well tested. Adding the missing closing brace allows it to compile and produces a working `ksh93` binary.

**Comment by krader1961** [comment]
I was going to just remove all references to, and uses of, `mmap()` and related functions and symbols. But that causes unexpected failures on Linux in the signal handling unit tests! WTF? So instead I'm going to limit the fix for this issue to just removing the IFFE tests for `MAP_ANON` support and mapping */dev/zero*. Instead just assume `MAP_ANON` is valid. Which is true for every platform I'm aware of that we care about today.
