### ISSUE TITLE
On OpenBSD `builtins -s` does not include `newgrp`

### ISSUE THREAD

**Issue by krader1961** [att/ast#861]
On OpenBSD `builtins -s` does not include `newgrp` so that recently added test fails. TBD is whether that command should be available as a builtin on OpenBSD. Or whether we need to make the test work regardless of whether or not it is a builtin.

**Comment by krader1961** [comment]
This is predicated on a build time feature test for a `newgrp` external command. That seems wrong given that it is a "special" builtin that should work regardless of whether an external command of the same name exists.

**Comment by krader1961** [comment]
FWIW, I think it is questionable whether `newgrp` should be a "special" builtin. Especially since using it has the effect of replacing the current shell process with a new process. Something that wouldn't happen if `newgrp` was an external command and you **did not** use `exec newgrp ...`. I can't even remember within +/- 5 years the last time I used the `newgrp` command but it was definitely before the year 2000.

**Comment by perette** [comment]
`newgrp` has been in these since ksh88.  I acknowledge it doesn't necessary provide much bonus; the implicit `exec` behavior doesn't buy much.  But taking it out would break existing scripts--unless an implicit `alias newgrp="exec $(whence -p newgrp)"` was done on initialization.

While on the topic, an issue with the built-in (well, any) `newgrp`: On error, it execs anyway, so on error the whole script dies; there's no option for error handling.  Fixing this so on error it returns an error code, would differentiate it from the external `newgrp`.
