### ISSUE TITLE
Build failure on OS X 10.9 and older: use of undeclared identifier 'AT_FDCWD'

### ISSUE THREAD

**Issue by ryandesign** [att/ast#941]
**Description of problem:**

On the somewhat older OS X 10.9 and earlier, [building ksh fails](https://build.macports.org/builders/ports-10.9_x86_64-builder/builds/68202/steps/install-port/logs/stdio) due to the use of `faccessat` and `AT_FDCWD` which weren't part of OS X until version 10.10.

**Ksh version:**

20181007

**How reproducible:**

Always

**Steps to reproduce:**
1. Build ksh on OS X 10.9 or older

**Actual results:**

```
../ast-7a4881196dac4ea2264ec0e8b95e6db7b4965ef9/src/lib/libast/port/astconf.c:483:61: warning: implicit declaration of function 'faccessat' is invalid in C99 [-Wimplicit-function-declaration]
                                if ((d = sfstruse(tmp)) && !eaccess(d, X_OK)) {
                                                            ^
./config_ast.h:238:23: note: expanded from macro 'eaccess'
#define eaccess(p, f) faccessat(AT_FDCWD, p, f, AT_EACCESS)
                      ^
../ast-7a4881196dac4ea2264ec0e8b95e6db7b4965ef9/src/lib/libast/port/astconf.c:483:61: error: use of undeclared identifier 'AT_FDCWD'
./config_ast.h:238:33: note: expanded from macro 'eaccess'
#define eaccess(p, f) faccessat(AT_FDCWD, p, f, AT_EACCESS)
                                ^
1 warning and 1 error generated.
```

**Expected results:**

Successful build.

**Additional info:**

**Comment by krader1961** [comment]
OS X 10.9 was released in October 2013; i.e., just five years ago. We should certainly try to support it. But this raises the question of how old an OS is that we want to support. The fish shell, for example, made a deliberate choice to drop support for OS X 10.6 (Snow Leopard) and earlier a year ago in order to take advantage of C++'11 improvements. It seems unlikely anyone who hasn't upgraded their OS in more than seven years is going to be interested in upgrading software installed on it such as `ksh`. Does MacPorts have a mechanism for specifying that a particular project is only supported by OS X version "y" or later? What is the oldest OS X release you expect a project to support by default?

**Comment by ryandesign** [comment]
On the MacPorts download web page, we currently display download links for the 4 most recent macOS versions prominently, with older versions hidden a bit. We expect most MacPorts users to be running a current version of macOS. But I also recognize that users sometimes need or want to use older OS versions, and that a package management system like MacPorts provides a way to breathe new life into older systems. For example, when the shellshock bug was discovered a few years ago, some of our users used MacPorts to install a patched version of bash on their older systems for which Apple did not issue bash updates.

On the Mac, not upgrading the OS isn't always a choice. Apple routinely drops support for older Macs in newer version of the OS. The first generation Intel Macs can't be upgraded past Snow Leopard. Second generation Intel Macs can't be upgraded past Lion. Yes, we may expect that a user will buy a newer Mac at some point, but even if they do, they may continue to use their old Mac as a secondary machine, and wish to install software on it. Apple also makes changes in the OS that may affect users. Snow Leopard was the last version to be able to run PowerPC software. Mojave is the last version that can run 32-bit software. Users may have older software that they still need to use, which for whatever reason is not compatible with newer OS versions, and for which no updated version is available.

I figured something as fundamental as a shell would want to be compatible with the widest range of systems possible but which OS versions you want to support is up to you. I know different developers have different goals for their projects so I wanted to let you know about this issue so you can decide how to proceed. If you want to support older systems, I can help you by reporting problems when I see them; if not, I can mark it as not working on those older systems.

In MacPorts we have no problem building software that uses newer language standards on older systems; MacPorts can install newer compiler toolchains as needed. But identifiers like `AT_FDCWD` are defined in system headers; using a newer toolchain won't solve that.

Just for fun, I installed fish 2.7.1 with MacPorts on a PowerBook G4 running Mac OS X 10.4. Works fine! We didn't have to patch it, though we do build it with a newer GCC for C++11 support.

**Comment by krader1961** [comment]
> I figured something as fundamental as a shell would want to be compatible with the widest range of systems possible but which OS versions you want to support is up to you.

That is definitely a goal. But since the project was orphaned by AT&T there hasn't been any concerted effort to keep it viable prior to @siteshwar's and my efforts beginning in mid 2017. So even though I happen to use macOS as my primary desktop system, and have one VM setup to run it for testing things, I don't personally care much about versions I no longer run. Which means that we depend on people like you to let us know there is a compatibility problem. The old AST/ksh code would build on old systems because that team of developers wanted the latest and greatest ksh release to work even on systems having a pre-ANSI C (i.e., K&R) compiler. Which made the project extremely hard to understand and modify. Which is why we are working to bring the project into the 21'st century while retaining a reasonable amount of backward compatibility.

> But I also recognize that users sometimes need or want to use older OS versions...

I'm doing that on my primary macOS server because the Indigo home automation software I use doesn't interact correctly with a USB device on macOS 10.13 (High Sierra). The question is how likely is it that someone running an OS release more than a few releases back is going to want to risk breaking their system by upgrading something like `ksh`. It seems to me the number is vanishingly close to zero if you exclude people doing macports/homebrew upgrades without understanding the consequences.

> ... though we do build it with a newer GCC for C++11 support.

Which is awesome but it implies that either you're also building and installing the necessary libraries to support the C++11 features or those features are implemented entirely by the compiler. Yes?

**Comment by ryandesign** [comment]
GCC includes the libstdc++ library, yes. We use GCC's libstdc++ on OS X 10.8 and older for C++11 support, since macOS libstdc++ is too old. On 10.9 and later, clang defaults to libc++ which supports C++11.
