### ISSUE TITLE
`signbit` prints 512 if number is negative

### ISSUE THREAD

**Issue by siteshwar** [att/ast#967]
**Description of problem:**
`signbit` prints `512` if number is negative

**Ksh version:**
2017.0.0-devel-1953-g89d7b802

**How reproducible:**
Always

**Steps to reproduce:**
```
echo $(( signbit(-1) ))
```

**Actual results:**
`512`

**Expected results:**
`1`

**Additional info:**
This bug is reproducible with `ksh 93u+`.

**Comment by krader1961** [comment]
Also, this isn't technically a bug since the underlying math(3) function only guarantees to return a non-zero value if the input is negative. It does not guarantee to return one in that case.


@siteshwar What leads you to believe this should output `1` rather than `512` or any other non-zero value?

**Comment by siteshwar** [comment]
> What leads you to believe this should output 1 rather than 512 or any other non-zero value?

Strictly speaking it may not be a bug, but it makes behavior more consistent with other math functions. For e.g. `iszero` returns either 0 or 1.
