### ISSUE TITLE
Add support for OpenIndiana

### ISSUE THREAD

**Issue by siteshwar** [att/ast#994]
There is a pull request to add `meson` in OpenIndiana (See https://github.com/OpenIndiana/oi-userland/pull/4502/). Once that is merged, we should be able to start supporting it.

**Comment by alarcher** [comment]
@siteshwar Out of curiosity, have you integrated the patches from solaris-useralnd?

**Comment by siteshwar** [comment]
@krader1961 has integrated some patches from Solaris (See https://github.com/att/ast/issues/122).

**Comment by krader1961** [comment]
That's good to know, @siteshwar, but what exactly are our action items? That is, what do we need to do to consider this issue resolved? Presumably if the OpenIndiana team attempts to build ksh from the source in this project and runs into problems they will open issues.  Is there something you think we can do proactively?

@alarcher FWIW I actually merged most of the patches from the Solaris team. As I documented in issue #122 there were a few that I rejected because they had nothing to do with ksh itself but rather how the project was packaged in Solaris. Or the patch didn't apply to the current source even with manual intervention.

**Comment by siteshwar** [comment]
> Is there something you think we can do proactively?

Yes, as soon as `meson` gets into OpenIndiana we should fix build failures (if any) and verify that build passes on it.

**Comment by krader1961** [comment]
See also issue #1178.

**Comment by krader1961** [comment]
FYI, I've been successfully building ksh on OpenIndiana and it passes the unit tests. This does require a custom `meson` command.

**Comment by krader1961** [comment]
For the record to build ksh on OpenIndiana (and presumably Solaris, Illumos, etc.) you need to install the Meson source. Then apply this [patch](https://github.com/mesonbuild/meson/pull/5477). Then do the usual `python3 ./setup.py --prefix=/usr/local`. See [Meson issue 5351](https://github.com/mesonbuild/meson/issues/5351). Once that is done I have been using the following sequence of commands. Starting with installing prerequisites:

```
sudo pkg install pkg:/developer/versioning/git
sudo pkg install pkg:/developer/gnu-binutils
sudo pkg install pkg:/developer/build/ninja
sudo pkg install pkg:/runtime/python-35
sudo pkg install pkg:/system/header
sudo pkg install pkg:/metapackages/build-essential
sudo pkg install pkg:/developer/gcc-8
sudo pkg install pkg:/developer/build/automake-115
```

Now do the build:

```
# Make sure PATH is setup. In particular we need the `ar` command from
# the /usr/xpg4/bin directory.
PATH=/usr/xpg4/bin:/usr/gnu/bin:$PATH

mkdir build
cd build
env CFLAGS=-m64 CC=gcc AR=/usr/gnu/bin/ar LD=/usr/gnu/bin/ld meson -Db_asneeded=false
env CFLAGS=-m64 CC=gcc AR=/usr/gnu/bin/ar LD=/usr/gnu/bin/ld ninja >x 2>&1
meson test
```

I don't yet know why I have to specify the same environment vars when running `ninja`. That should not be necessary.
